// Handbuch, Quellsprache Deutsch. Beschriftungen in **…** müssen wörtlich
// den Strings aus lib/i18n.ts entsprechen (die Bilder zeigen sie).
// Kapitel-ids und Bilddateien sind in allen vier Sprachen gleich.
import type { Kapitel } from "./typ";

const kapitel: Kapitel[] = [
  {
    id: "start",
    titel: "Erste Schritte",
    kurz: "Was die App macht, wie sie aufgebaut ist und wie du in fünf Minuten zum ersten Transkript kommst.",
    bloecke: [
      { art: "p", text: "ResearchTranscript macht aus einer Aufnahme ein Transkript mit Sprechern und Zeitmarken. Alles läuft auf deinem Mac. Es gibt kein Konto, keine Cloud und keine Netzverbindung." },
      { art: "h", text: "Die drei Bereiche" },
      { art: "liste", punkte: [
        "**AI-Transkript**: Aufnahmen hineinziehen, Sprecherzahl wählen, transkribieren lassen.",
        "**Human-Editor**: die Bibliothek aller Transkripte. Ein Klick öffnet ein Transkript im Editor, wo du hörst, korrigierst, Sprecher benennst und exportierst.",
        "**Einstellungen**: Speicherort, Standard-Optionen, Zotero, Datenschutz und Lizenzen.",
      ] },
      { art: "h", text: "Der erste Start" },
      { art: "p", text: "Beim ersten Start fragt die App unter **Speicherort wählen**, wo deine Transkripte liegen sollen. **Empfohlenen Ort verwenden** legt den Ordner in deinen Dokumenten an. Mit **Anderen Ordner wählen …** nimmst du einen eigenen Ordner, zum Beispiel auf einem verschlüsselten Laufwerk. Die App merkt sich die Freigabe für diesen Ordner." },
      { art: "h", text: "In fünf Minuten zum Transkript" },
      { art: "schritte", punkte: [
        "Öffne **AI-Transkript** und ziehe eine Audio- oder Videodatei auf das Feld **Audio-Dateien hierher ziehen**.",
        "Wähle bei der Datei die Zahl der Sprechenden.",
        "Klicke auf **Transkription starten**. Die Kopfzeile oben links zeigt Laufzeit und Schätzung.",
        "Ist der Lauf **Fertig**, öffne das Transkript mit **Bearbeiten** im Editor.",
        "Höre mit der [[Leertaste]], korrigiere den Text, benenne die Sprecher im Seitenfeld **Sprecher**.",
        "Wähle unter **Export** das Format, das du brauchst.",
      ] },
      { art: "bild", datei: "02-ai-transkript", text: "AI-Transkript: oben die Optionen, darunter die Dateien, die auf den Start warten, und die Batch-Liste der Läufe." },
      { art: "hinweis", text: "Dieses Hilfefenster bleibt neben der Arbeit offen. Du öffnest es über das Menü **Help**, mit [[⌘]] [[?]] oder mit dem Fragezeichen oben rechts im Hauptfenster." },
    ],
  },
  {
    id: "transkribieren",
    titel: "Transkribieren",
    kurz: "Dateien einreihen, Sprecherzahl und Optionen wählen, Läufe verfolgen und abbrechen.",
    bloecke: [
      { art: "h", text: "Dateien hinzufügen" },
      { art: "p", text: "Ziehe eine oder mehrere Dateien auf das Feld **Audio-Dateien hierher ziehen** oder klicke darauf und wähle sie aus. Unterstützt sind MP3, WAV, M4A, OGG und FLAC, als Video MP4 und MOV mit H.264 oder HEVC. Bei Videos liest die App den Ton; das Bild läuft später im Editor stumm mit." },
      { art: "h", text: "Optionen" },
      { art: "tabelle", kopf: ["Option", "Bedeutung"], zeilen: [
        ["**Whisper-Modell**", "Das Sprachmodell. Mitgeliefert ist large-v3-turbo. Eigene Modelle erscheinen hier, sobald sie im Modelle-Ordner liegen (Kapitel «Eigene Modelle»)."],
        ["**Sprache**", "Sprache der Aufnahme: de, en, fr, it, es oder auto. Eine feste Sprache ist zuverlässiger als die automatische Erkennung."],
        ["**Sprecher** · **Vorgabe für neue Dateien**", "Sprecherzahl, die eine einzeln hinzugefügte Datei übernimmt: 1 bis 6 oder **Automatisch**. Bei 1 entfällt die Sprechererkennung."],
        ["**Trennung**", "Wie streng Stimmen unterschieden werden: **Locker**, **Normal**, **Streng**, **Sehr streng**. Streng trennt ähnliche Stimmen eher in zwei Sprecher, locker fasst sie eher zusammen. Das wirkt vor allem bei **Automatisch**."],
      ] },
      { art: "h", text: "Bereit zum Start: Sprecherzahl je Datei" },
      { art: "p", text: "Jede Datei in der Liste **Bereit zum Start** hat ihre eigene Sprecherzahl. Ziehst du mehrere Dateien auf einmal hinein, musst du sie je Datei wählen. Solange bei einer Datei **Sprecherzahl wählen** steht, startet kein Lauf. Die Zahl bestimmt das Ergebnis stark und steht später im Journal des Transkripts. **Aus der Liste nehmen** entfernt eine Datei wieder. Die Liste bleibt über einen Neustart der App erhalten." },
      { art: "h", text: "Läufe verfolgen" },
      { art: "p", text: "**Transkription starten** schickt alle wartenden Dateien in die **Batch-Liste**. Ein Lauf durchläuft die Schritte **Konvertiere Audio …**, **Erkenne Sprecher …**, **Transkribiere …** und **Speichere …**. Lange Aufnahmen werden in Blöcken transkribiert; die Anzeige nennt den Block. Oben links läuft die Zeit mit, ab etwa fünf Prozent Fortschritt mit einer Schätzung der Gesamtdauer." },
      { art: "liste", punkte: [
        "**Abbrechen** beendet einen Lauf. Während der Sprechererkennung wirkt der Abbruch erst, wenn dieser Schritt fertig ist.",
        "**Bearbeiten** öffnet ein fertiges Transkript im Editor.",
        "Wie viele Läufe gleichzeitig arbeiten, legst du in den Einstellungen unter **Gleichzeitige Läufe** fest. Mehrere Läufe teilen sich dieselbe Grafikeinheit und sind zusammen nicht schneller als nacheinander.",
      ] },
      { art: "hinweis", text: "Richtwert: Auf einem Mac mit Apple Silicon braucht eine Stunde Aufnahme wenige Minuten. Du kannst währenddessen im Editor an anderen Transkripten arbeiten." },
    ],
  },
  {
    id: "bibliothek",
    titel: "Bibliothek",
    kurz: "Alle Transkripte an einem Ort: öffnen, umbenennen, importieren, löschen.",
    bloecke: [
      { art: "p", text: "Der Bereich **Human-Editor** zeigt zuerst die Bibliothek. Jede Zeile nennt Name, Dauer, Zahl der Sprecher und Segmente. Ein Klick öffnet das Transkript im Editor. Vom Editor kommst du mit **Bibliothek** oder einem Klick auf **Human-Editor** zurück." },
      { art: "bild", datei: "03-bibliothek", text: "Die Bibliothek im Bereich Human-Editor." },
      { art: "liste", punkte: [
        "**Umbenennen …** ändert den Namen des Transkripts. Der Name erscheint in Exporten und Dateinamen.",
        "**Löschen …** verschiebt das Transkript in den Papierkorb der Bibliothek. Nichts wird endgültig gelöscht; der Ordner `_papierkorb` liegt im Bibliotheksordner.",
        "**Im Finder zeigen** öffnet den Ordner des Transkripts.",
        "**Transkript importieren (VTT/CSV/enrich) …** übernimmt ein vorhandenes Transkript. Danach fragt die App nach der passenden Audiodatei; mit Abbrechen importierst du ohne Ton.",
      ] },
      { art: "p", text: "Ein enrich-Dossier (.enrich) kannst du auch per Doppelklick im Finder oder durch Ziehen auf das App-Symbol öffnen." },
      { art: "hinweis", text: "Die App startet mit dem Bereich und dem Transkript, mit dem du sie beendet hast, an derselben Zeile." },
    ],
  },
  {
    id: "editor",
    titel: "Editor: Text und Turns",
    kurz: "Text korrigieren, Turns teilen, verbinden, einfügen und löschen, Startzeiten setzen.",
    bloecke: [
      { art: "p", text: "Der Editor zeigt je Zeile ein Segment: Abspielknopf, Startzeit, Sprecher, Text und rechts die Zeilenaktionen. Die aktive Zeile ist hervorgehoben; ihre Zeit läuft beim Abspielen in Hundertstelsekunden mit. Dieselbe Zeit steht gross oben links und klein unten rechts." },
      { art: "bild", datei: "01-editor", text: "Der Editor: Transkript links, Seitenfeld rechts, unten Wellenform und Steuerzeile." },
      { art: "h", text: "Text bearbeiten" },
      { art: "p", text: "Klicke in den Text und schreibe. Die App speichert von selbst; oben steht **Speichert …** und danach **Gespeichert** mit der Uhrzeit. Vor jedem Speichern legt sie den alten Stand im Ordner `history` des Transkripts ab (die letzten 30)." },
      { art: "h", text: "Turns teilen, einfügen, verbinden, löschen" },
      { art: "tasten", zeilen: [
        ["[[Enter]] mitten im Text", "Teilt das Segment am Cursor. Der zweite Teil bekommt die geschätzte Zeit der Schnittstelle."],
        ["[[Enter]] am Textende", "Legt danach einen neuen, leeren Turn an."],
        ["[[⌥]] [[Enter]]", "Zwischenruf: legt einen neuen Turn mit der Zeit der aktuellen Abspielposition an und setzt den Cursor hinein. Geht auch mitten im Tippen."],
        ["[[⌫]] am Textanfang", "Verbindet das Segment mit dem vorigen."],
        ["[[⌫]] im leeren Feld", "Löscht das Segment."],
      ] },
      { art: "p", text: "Dieselben Aktionen findest du als Symbole rechts in der Zeile: **Am Cursor teilen**, **Mit vorigem verbinden**, **Segment löschen** und **Memo zu dieser Zeile**." },
      { art: "bild", datei: "11-zeile", text: "Eine Zeile: Abspielknopf, Startzeit, Sprecher, Text, Aktionen. Der rote Punkt zeigt ein Memo." },
      { art: "h", text: "Startzeit bearbeiten" },
      { art: "p", text: "Klicke auf die Zeit einer Zeile. Gib die neue Startzeit als hh:mm:ss.hh ein, zum Beispiel 00:19:10.45, und bestätige mit [[Enter]]. [[Esc]] bricht ab. Kürzere Eingaben wie 19:10 oder 75.5 gehen auch. Die Zeile ordnet sich nach ihrer neuen Zeit ein." },
      { art: "h", text: "Sprecher einer Zeile ändern" },
      { art: "p", text: "Ein Klick auf das Sprecher-Schild öffnet das Menü. Die zuletzt gewählten Sprecher stehen oben. **Neuer Sprecher** legt eine neue Person an, **ohne Sprecher** entfernt die Zuordnung." },
      { art: "h", text: "Schriftgrösse" },
      { art: "p", text: "Die Grösse des Turn-Texts stellst du in den Einstellungen unter **Schrift Turn-Text** ein." },
    ],
  },
  {
    id: "wiedergabe",
    titel: "Wiedergabe und Wellenform",
    kurz: "Abspielen, springen, Tempo, Schleife, Folgen, Wellenform zoomen, Video.",
    bloecke: [
      { art: "bild", datei: "09-wiedergabe", text: "Wellenform mit Memo-Markern, darunter die Steuerzeile: Transport, Tempo, Wiedergabe-Modi, rechts die Zeit." },
      { art: "h", text: "Steuerzeile" },
      { art: "tabelle", kopf: ["Element", "Wirkung"], zeilen: [
        ["Transport", "5 s zurück, Abspielen oder Pause, 5 s vor."],
        ["Tempo − Wert +", "**Langsamer** und **Schneller** in den Stufen 0,75× bis 2×. Ein Klick auf den Wert stellt 1× wieder her."],
        ["**Schleife**", "Wiederholt das aktive Segment, bis du die Schleife ausschaltest."],
        ["**Folgen**", "Die Liste folgt der Wiedergabe: Die aktive Zeile bleibt im mittleren Bereich des Fensters."],
      ] },
      { art: "p", text: "Der Abspielknopf vorn in jeder Zeile spielt **Ab hier** und hält beim zweiten Klick wieder an." },
      { art: "h", text: "Wellenform" },
      { art: "p", text: "Die Wellenform zeigt die Aufnahme in den Farben der Sprecher. Die senkrechte Linie ist die Abspielposition." },
      { art: "liste", punkte: [
        "Klicken oder Ziehen setzt die Abspielposition.",
        "[[⌘]] + Scrollrad oder die Zwei-Finger-Spreizgeste zoomt um den Zeiger.",
        "Horizontal scrollen oder [[⇧]] + Scrollrad verschiebt den Ausschnitt.",
        "Ein Doppelklick zeigt wieder die ganze Aufnahme.",
        "Beim Abspielen rückt der Ausschnitt nach, sobald die Linie den Rand erreicht.",
        "Rote Punkte in der oberen Spur sind Memos. Der Zeiger darüber zeigt den Text, ein Klick öffnet das Memo.",
      ] },
      { art: "h", text: "Video" },
      { art: "p", text: "Bei einer Videoquelle läuft das Bild stumm neben dem Transkript mit; der Ton kommt aus der Tonspur des Transkripts. Bei 2× bleibt das Bild stehen, bis du langsamer stellst." },
      { art: "p", text: "Steht in der Steuerzeile **Kein Audio verknüpft**, wurde das Transkript ohne Tondatei importiert." },
    ],
  },
  {
    id: "sprecher",
    titel: "Sprecher",
    kurz: "Sprecher benennen, einfärben, anhören, zusammenführen und leere Zeilen zuweisen.",
    bloecke: [
      { art: "p", text: "Das Seitenfeld **Sprecher** listet alle Personen des Transkripts mit der Zahl ihrer Segmente. Nach dem Transkribieren heissen sie zunächst nach ihrer Nummer." },
      { art: "bild", datei: "05-sprecherfarbe", text: "Seitenfeld Sprecher mit geöffneter Farbwahl." },
      { art: "liste", punkte: [
        "**Umbenennen**: Schreibe den Namen ins Feld. Er ändert sich sofort in allen Zeilen und Exporten.",
        "**Farbe wählen**: Der farbige Kreis öffnet die Palette. Die Farbe gilt für Schild, Wellenform und den REFI-QDA-Export.",
        "**Hörprobe**: spielt einen kurzen Ausschnitt dieser Stimme, damit du sie erkennst.",
        "**Zusammenführen in …**: hängt alle Segmente dieser Person an eine andere. Das hilft, wenn die Erkennung eine Stimme in zwei geteilt hat.",
        "**Allen ohne Sprecher zuweisen**: gibt allen Zeilen ohne Sprecher diese Person.",
      ] },
      { art: "hinweis", text: "Sprecher sind eigene Einträge, kein Text vor der Zeile. Umbenennen und Zusammenführen ändern deshalb nie den Wortlaut." },
    ],
  },
  {
    id: "suchen",
    titel: "Suchen und Ersetzen",
    kurz: "Wörter finden, einzeln prüfen und ersetzen, zum Beispiel für Pseudonyme.",
    bloecke: [
      { art: "p", text: "Das Seitenfeld **Suchen** durchsucht den Text des offenen Transkripts. Trage unter **Suchen nach** den Begriff ein und, wenn du ersetzen willst, unter **Ersetzen durch** den neuen Text." },
      { art: "bild", datei: "04-suchen-ersetzen", text: "Suchen und Ersetzen: Die Treffer sind im Transkript markiert." },
      { art: "liste", punkte: [
        "**Voriger Treffer** und **Nächster Treffer** springen durch die Fundstellen; die Anzeige nennt die Position, etwa 3 von 12.",
        "**Ersetzen** ersetzt den aktuellen Treffer, **Überspringen** lässt ihn stehen und geht weiter.",
        "**Alle ersetzen** ersetzt jeden Treffer auf einmal.",
        "**Worttrennung überlesen** findet auch getrennt geschriebene Formen wie «Werk- statt».",
        "**Groß-/Kleinschreibung beachten** unterscheidet «Haus» und «haus».",
      ] },
      { art: "hinweis", text: "Die Suche ist buchstabengetreu: keine Übersetzung, keine Stammformen. Für Pseudonyme suchst du also jede Schreibweise eines Namens einzeln." },
    ],
  },
  {
    id: "memos",
    titel: "Memos",
    kurz: "Eigene Notizen je Zeile, getrennt vom Wortlaut, mit Export nach CSV und REFI-QDA.",
    bloecke: [
      { art: "p", text: "Ein Memo ist deine Notiz zu einer Zeile: eine Beobachtung, eine Rückfrage, ein erster Gedanke zur Auswertung. Es gehört dir und nicht zum Wortlaut." },
      { art: "bild", datei: "08-memo", text: "Das Memo einer Zeile." },
      { art: "schritte", punkte: [
        "Klicke rechts in der Zeile auf **Memo zu dieser Zeile**.",
        "Schreibe die Notiz und bestätige mit **Sichern** oder [[⌘]] [[Enter]].",
        "**Memo löschen** entfernt es wieder.",
      ] },
      { art: "p", text: "Eine Zeile mit Memo trägt einen roten Punkt am Symbol. In der Wellenform erscheint an ihrer Stelle ein roter Marker." },
      { art: "tabelle", kopf: ["Export", "Was mit dem Memo geschieht"], zeilen: [
        ["CSV", "Eigene Spalte «Memo». Mehrere Memos eines Turns stehen mit « | » getrennt."],
        ["REFI-QDA", "Memo an der codierten Stelle; ATLAS.ti und MAXQDA zeigen es dort an."],
        ["VTT, TXT", "Nicht enthalten."],
        ["enrich-Dossier", "Noch nicht enthalten."],
      ] },
    ],
  },
  {
    id: "metadaten",
    titel: "Metadaten und Zotero",
    kurz: "Titel, Datum, Interviewende und Citekey aus der lokalen Zotero-Bibliothek übernehmen.",
    bloecke: [
      { art: "p", text: "Im Seitenfeld **Metadaten** verknüpfst du ein Transkript mit einem Eintrag deiner Zotero-Bibliothek. Titel, Datum, Interviewer:in und Citekey stehen dann im enrich-Dossier. Zotero wird nur gelesen und nie verändert; es kann dabei geöffnet bleiben." },
      { art: "h", text: "Einmal freischalten" },
      { art: "schritte", punkte: [
        "Öffne **Einstellungen** und die Karte **Zotero**.",
        "Schalte **Lokale Zotero-Datenbank lesen erlauben** ein.",
        "Wähle mit **Ändern …** den Zotero-Ordner, meist `Zotero` in deinem Benutzerordner. Die App braucht diese Freigabe, weil sie in einer geschützten Umgebung läuft.",
        "Steht darunter **Gefunden**, ist die Datenbank lesbar.",
      ] },
      { art: "h", text: "Verknüpfen" },
      { art: "schritte", punkte: [
        "Öffne im Editor das Seitenfeld **Metadaten**.",
        "Suche nach Titel, Jahr, Name oder Citekey.",
        "Wähle den Eintrag und klicke **Verknüpfen**.",
        "Lege unter **Welche Personen kommen ins Transkript?** die Rollen fest.",
      ] },
      { art: "p", text: "**Neu laden** holt geänderte Angaben aus Zotero, **In Zotero zeigen** öffnet den Eintrag dort, **Lösen** trennt die Verknüpfung." },
      { art: "hinweis", text: "Die befragte Seite (interviewee, guest, castMember) ist nicht vorausgewählt. Ein pseudonymisiertes Transkript soll ihren Namen nicht über Zotero bekommen." },
    ],
  },
  {
    id: "export",
    titel: "Export",
    kurz: "Welches Format wofür: VTT, CSV, TXT, REFI-QDA und enrich-Dossier.",
    bloecke: [
      { art: "p", text: "Oben im Editor öffnet **Export** die Liste der Formate. Nach der Wahl fragt die App nach dem Speicherort. Exporte sind abgeleitet: Das Transkript in der Bibliothek bleibt die Quelle, du kannst jederzeit neu exportieren." },
      { art: "bild", datei: "06-export", text: "Die Exportformate im Editor." },
      { art: "tabelle", kopf: ["Format", "Inhalt", "Wofür"], zeilen: [
        ["VTT", "Untertitel mit Zeiten in Millisekunden, Sprecher als Voice-Tag. Sehr kurze Stellen werden zu lesbaren Untertiteln verbunden, lange geteilt.", "Videoplayer, Schnittprogramme, Wiederimport."],
        ["CSV", "Je Turn eine Zeile: Time-in, Time-out, Speaker, Text, Memo. Zeiten als hh:mm:ss.hh.", "Tabellen, eigene Auswertung, Wiederimport."],
        ["TXT", "Fliesstext, je Turn ein Absatz mit Sprechername. Ohne Zeiten.", "Lesen, Zitieren, Weitergabe."],
        ["**REFI-QDA für ATLAS.ti (.qdpx.zip)**", "Projektdatei mit Text, Ton, Zeitmarken je Äusserung, Sprechern als Codes und Memos.", "ATLAS.ti, MAXQDA, NVivo."],
        ["**REFI-QDA mit Video (.qdpx.zip)**", "Wie oben, mit der Videodatei statt der Tonspur. Nur bei Videoquellen.", "Videoanalyse in QDA-Software."],
        ["**enrich-Dossier (.enrich)**", "Transkript, Ton als MP3, Zotero-Metadaten und ein Journal, wer wann was bearbeitet hat.", "Weiterarbeit in enrich, Archiv."],
      ] },
      { art: "hinweis", text: "Der REFI-QDA-Export ist ein Zip. Entpacke es: Darin liegen die Projektdatei `.qdpx` und ein Ordner mit dem Medium. Importiere die `.qdpx`-Datei in deine QDA-Software und lass den Medienordner daneben liegen." },
    ],
  },
  {
    id: "einstellungen",
    titel: "Einstellungen",
    kurz: "Alle Karten der Einstellungen und was ihre Optionen bewirken.",
    bloecke: [
      { art: "bild", datei: "07-einstellungen", text: "Die Einstellungen." },
      { art: "h", text: "Speicherort" },
      { art: "p", text: "Der Bibliotheksordner. Je Transkript entsteht ein Unterordner mit Transkript, Audio und Verlauf. **Ändern …** wählt einen anderen Ordner; vorhandene Transkripte verschiebt die App dabei nicht. **Im Finder zeigen** öffnet den Ordner." },
      { art: "h", text: "Standard-Optionen" },
      { art: "tabelle", kopf: ["Option", "Bedeutung"], zeilen: [
        ["**Whisper-Modell**", "Vorgabe für neue Läufe."],
        ["**Sprache**", "Vorgabe für die Sprache der Aufnahmen."],
        ["**Gleichzeitige Läufe**", "1 bis 4. Empfohlen ist **1 — nacheinander**."],
        ["**Oberflächen-Sprache**", "Deutsch, English, Français, Italiano. Gilt sofort, auch für dieses Hilfefenster."],
        ["**Schrift Turn-Text**", "Schriftgrösse des Transkripttexts im Editor."],
      ] },
      { art: "h", text: "Identität im Dossier" },
      { art: "p", text: "**E-Mail als User-ID (freiwillig)** schreibt deine Adresse ins Journal jedes enrich-Dossiers, das du exportierst. Sie verlässt den Rechner nur mit dieser Datei. Die **Kennung dieser Installation** ist zufällig und hat keinen Bezug zu Gerät oder Person; **Neu erzeugen** vergibt eine neue." },
      { art: "h", text: "Zotero" },
      { art: "p", text: "Freischaltung und Ordner der Zotero-Datenbank, siehe Kapitel «Metadaten und Zotero»." },
      { art: "h", text: "Datenschutz" },
      { art: "p", text: "Fasst zusammen, dass alles lokal bleibt. **Datenschutzerklärung** öffnet den vollständigen Text. **Protokoll öffnen** zeigt das lokale Protokoll der App; es hilft bei der Fehlersuche und wird nie verschickt." },
      { art: "h", text: "Lizenzen, ResearchTranscript, Formate, BIAS.City" },
      { art: "p", text: "Diese Karten nennen die mitgelieferten Bestandteile und ihre Lizenzen (**Alle Lizenzen (Liste)**), den Quellcode, die Spezifikationen der Exportformate und das Institut hinter der App." },
      { art: "hinweis", text: "Hell und Dunkel folgen der Einstellung von macOS unter Systemeinstellungen › Erscheinungsbild." },
    ],
  },
  {
    id: "modelle",
    titel: "Eigene Modelle",
    kurz: "Weitere whisper.cpp-Modelle verwenden, zum Beispiel für Schweizerdeutsch.",
    bloecke: [
      { art: "p", text: "Die App bringt das Modell large-v3-turbo mit. Du kannst weitere whisper.cpp-Modelle im ggml-Format verwenden, etwa ein Feintuning für Schweizerdeutsch oder eine kleinere, quantisierte Variante." },
      { art: "schritte", punkte: [
        "Öffne **Einstellungen**, Karte **Standard-Optionen**, Abschnitt **Eigene Modelle**.",
        "Klicke **Im Finder zeigen** und lege die Datei in diesen Ordner. Der Name muss dem Muster `ggml-….bin` folgen.",
        "Klicke **Neu einlesen**. Das Modell erscheint in der Auswahl **Whisper-Modell**, markiert als **eigenes**.",
      ] },
      { art: "p", text: "Ein eigenes Modell mit demselben Namen ersetzt das mitgelieferte. Die App lädt selbst nie Modelle herunter." },
      { art: "h", text: "Wenn ein Modell nicht erscheint" },
      { art: "tabelle", kopf: ["Meldung", "Was zu tun ist"], zeilen: [
        ["**wird noch kopiert**", "Warten, bis der Finder fertig ist, dann **Neu einlesen**."],
        ["**kein whisper.cpp-Modell (ggml)**", "Die Datei hat ein anderes Format, zum Beispiel PyTorch oder Core ML. Du brauchst die ggml-Fassung."],
        ["**unvollständig (zu klein für ein Modell)**", "Der Download ist abgebrochen. Lade die Datei neu."],
        ["**liegt nur in iCloud**", "Im Finder über das Wolkensymbol herunterladen."],
        ["**wird ignoriert (Name muss ggml-….bin sein)**", "Datei umbenennen."],
      ] },
      { art: "hinweis", text: "Womit transkribiert wurde, steht in jedem Transkript im Journal. Eigene Modelle gehören nicht zur Liste im Datenschutzblatt der Website; nenne sie in deiner Dokumentation selbst." },
    ],
  },
  {
    id: "tasten",
    titel: "Tastenkürzel",
    kurz: "Alle Kürzel des Editors, auch für Fusspedale.",
    bloecke: [
      { art: "p", text: "Im Editor gibt es zwei Lagen: Ausserhalb eines Textfelds steuern einfache Tasten die Wiedergabe. Beim Tippen gehören die Tasten dem Text; dieselben Befehle liegen dann auf [[⌥]]. [[Esc]] verlässt das Textfeld." },
      { art: "h", text: "Wiedergabe" },
      { art: "tabelle", kopf: ["Befehl", "Ausserhalb des Texts", "Beim Tippen"], zeilen: [
        ["Abspielen / Pause", "[[Leertaste]] oder [[K]]", "[[⇧]] [[Leertaste]], [[⌥]] [[Leertaste]] oder [[⌥]] [[K]]"],
        ["5 s zurück", "[[J]] oder [[←]]", "[[⌥]] [[J]]"],
        ["5 s vor", "[[L]] oder [[→]]", "[[⌥]] [[L]]"],
        ["Voriger / nächster Turn", "[[↑]] / [[↓]]", "[[⌥]] [[↑]] / [[⌥]] [[↓]] – der Cursor wandert mit"],
        ["Voriger / nächster Turn (Fusspedal)", "[[fn]] [[↑]] / [[fn]] [[↓]] (Bild auf / Bild ab)", "ebenso"],
        ["Schleife ein / aus", "[[Ctrl]] [[L]]", "[[Ctrl]] [[L]]"],
        ["Nächstes Tempo", "[[Ctrl]] [[X]]", "[[Ctrl]] [[X]]"],
      ] },
      { art: "h", text: "Text und Turns" },
      { art: "tasten", zeilen: [
        ["[[Enter]]", "Segment am Cursor teilen; am Textende: neuer Turn."],
        ["[[⌥]] [[Enter]]", "Zwischenruf an der Abspielposition einfügen."],
        ["[[⌫]] am Textanfang", "Mit dem vorigen Segment verbinden."],
        ["[[⌫]] im leeren Feld", "Segment löschen."],
        ["[[Esc]]", "Textfeld verlassen; danach gelten wieder die einfachen Tasten."],
        ["[[⌘]] [[Z]] / [[⇧]] [[⌘]] [[Z]]", "Widerrufen und Wiederholen im Textfeld."],
      ] },
      { art: "h", text: "Weitere" },
      { art: "tasten", zeilen: [
        ["[[Enter]] / [[Esc]] im Zeitfeld", "Startzeit übernehmen / verwerfen."],
        ["[[⌘]] [[Enter]] im Memo", "Memo sichern."],
        ["[[⌘]] + Scrollrad auf der Wellenform", "Zoomen."],
        ["[[⇧]] + Scrollrad auf der Wellenform", "Ausschnitt verschieben."],
        ["Doppelklick auf die Wellenform", "Ganze Aufnahme zeigen."],
        ["[[⌘]] [[?]]", "Diese Hilfe öffnen."],
      ] },
      { art: "h", text: "Fusspedal" },
      { art: "p", text: "Ein Fusspedal, das Tasten sendet, belegst du in seiner Software mit Bild auf und Bild ab für den Turn-Wechsel und mit [[⇧]] [[Leertaste]] für Abspielen und Pause. Diese Kürzel wirken auch, während du schreibst." },
    ],
  },
  {
    id: "daten",
    titel: "Daten, Datenschutz und Fehlersuche",
    kurz: "Wo deine Daten liegen, was die App nie tut und was bei Problemen hilft.",
    bloecke: [
      { art: "h", text: "Wo die Daten liegen" },
      { art: "p", text: "Alles liegt im Bibliotheksordner, je Transkript ein Unterordner:" },
      { art: "tabelle", kopf: ["Datei", "Inhalt"], zeilen: [
        ["`transkript.json`", "Das Transkript: Segmente, Sprecher, Memos, Journal. Die eine Quelle; Exporte sind davon abgeleitet."],
        ["`audio.…`", "Kopie der Aufnahme, bei Videos zusätzlich die Videodatei."],
        ["`history/`", "Die letzten 30 Stände vor jedem Speichern."],
        ["`wellenform.json`", "Zwischenspeicher der Wellenform; entsteht bei Bedarf neu."],
        ["`_papierkorb/`", "Gelöschte Transkripte, im Bibliotheksordner. Leeren kannst du ihn im Finder."],
      ] },
      { art: "hinweis", text: "Für Backups sicherst du den Bibliotheksordner. Für einen Umzug auf einen anderen Mac kopierst du ihn und wählst ihn dort als Speicherort." },
      { art: "h", text: "Was die App nie tut" },
      { art: "liste", punkte: [
        "Sie überträgt nichts: keine Aufnahmen, keine Texte, keine Nutzungsdaten.",
        "Sie lädt keine Modelle oder Programmteile nach.",
        "Sie liest nur Ordner, die du ausgewählt hast, und Dateien, die du hineinziehst.",
        "Sie verändert Zotero nicht.",
      ] },
      { art: "h", text: "Wenn etwas nicht geht" },
      { art: "tabelle", kopf: ["Beobachtung", "Was hilft"], zeilen: [
        ["Banner «Die Verarbeitung antwortet … nicht mehr»", "**App neu starten**. Laufende Arbeit ist gespeichert."],
        ["Lauf endet mit **Fehlgeschlagen**", "Die Meldung nennt den Grund, etwa ein nicht unterstütztes Videoformat. Wandle die Datei in MP4 (H.264) oder ein Audioformat um."],
        ["Falsche Zahl von Sprechern", "Transkribiere neu mit fester Sprecherzahl statt **Automatisch**, oder führe Sprecher im Editor zusammen."],
        ["Viele Fehler bei Dialekt oder Fachsprache", "Feste **Sprache** wählen; für Schweizerdeutsch ein eigenes Modell verwenden."],
        ["Zotero wird nicht gefunden", "In den Einstellungen den Zotero-Ordner über **Ändern …** neu wählen."],
        ["Etwas anderes", "**Einstellungen › Datenschutz › Protokoll öffnen** und die letzten Zeilen ansehen oder mitschicken."],
      ] },
      { art: "p", text: "Fragen und Fehlerberichte: bias.city/researchtranscript oder die Issues im GitHub-Repository bias-city/ResearchTranscript." },
    ],
  },
];

export default kapitel;
