// English translation of de.ts (source language: German). Chapter ids and image files must stay identical; **…** labels must match the en: strings in lib/i18n.ts verbatim.
import type { Kapitel } from "./typ";

const kapitel: Kapitel[] = [
  {
    id: "start",
    titel: "Getting started",
    kurz: "What the app does, how it is organised, and how to get your first transcript in five minutes.",
    bloecke: [
      { art: "p", text: "ResearchTranscript turns a recording into a transcript with speakers and timestamps. Everything runs on your Mac. There is no account, no cloud and no network connection." },
      { art: "h", text: "The three areas" },
      { art: "liste", punkte: [
        "**AI Transcript**: drop in recordings, choose the number of speakers, let the app transcribe.",
        "**Human Editor**: the library of all transcripts. One click opens a transcript in the editor, where you listen, correct, name speakers and export.",
        "**Settings**: storage location, default options, Zotero, privacy and licences.",
      ] },
      { art: "h", text: "The first launch" },
      { art: "p", text: "On first launch the app asks under **Choose storage** where your transcripts should be kept. **Use recommended location** creates the folder in your Documents. With **Choose another folder …** you pick a folder of your own, for example on an encrypted drive. The app remembers the permission for this folder." },
      { art: "h", text: "A transcript in five minutes" },
      { art: "schritte", punkte: [
        "Open **AI Transcript** and drag an audio or video file onto the **Drop audio files here** field.",
        "Choose the number of speakers for the file.",
        "Click **Start transcription**. The header at the top left shows elapsed time and an estimate.",
        "When the run is **Done**, open the transcript in the editor with **Edit**.",
        "Listen with [[Space]], correct the text, name the speakers in the **Speakers** side panel.",
        "Under **Export**, choose the format you need.",
      ] },
      { art: "bild", datei: "02-ai-transkript", text: "AI Transcript: the options at the top, below them the files waiting to start, and the batch list of runs." },
      { art: "hinweis", text: "This help window stays open next to your work. You open it from the **Help** menu, with [[⌘]] [[?]] or with the question mark at the top right of the main window." },
    ],
  },
  {
    id: "transkribieren",
    titel: "Transcribing",
    kurz: "Queue files, choose speaker count and options, follow runs and cancel them.",
    bloecke: [
      { art: "h", text: "Adding files" },
      { art: "p", text: "Drag one or more files onto the **Drop audio files here** field, or click it and select them. Supported are MP3, WAV, M4A, OGG and FLAC, and as video MP4 and MOV with H.264 or HEVC. For videos the app reads the sound; the picture later plays muted alongside in the editor." },
      { art: "h", text: "Options" },
      { art: "tabelle", kopf: ["Option", "Meaning"], zeilen: [
        ["**Whisper model**", "The speech model. large-v3-turbo is included. Your own models appear here as soon as they are in the models folder (chapter “Your own models”)."],
        ["**Language**", "Language of the recording: de, en, fr, it, es or auto. A fixed language is more reliable than automatic detection."],
        ["**Speakers** · **Default for new files**", "Speaker count that a single added file takes over: 1 to 6 or **Automatic**. With 1, speaker detection is skipped."],
        ["**Separation**", "How strictly voices are told apart: **Loose**, **Normal**, **Strict**, **Very strict**. Strict tends to split similar voices into two speakers, loose tends to merge them. This mainly affects **Automatic**."],
      ] },
      { art: "h", text: "Ready to start: speaker count per file" },
      { art: "p", text: "Every file in the **Ready to start** list has its own speaker count. If you drop in several files at once, you have to choose it for each file. As long as a file shows **Choose speaker count**, no run starts. The number strongly shapes the result and is later recorded in the transcript’s journal. **Remove from list** takes a file out again. The list survives a restart of the app." },
      { art: "h", text: "Following runs" },
      { art: "p", text: "**Start transcription** sends all waiting files to the **Batch list**. A run goes through the steps **Converting audio …**, **Detecting speakers …**, **Transcribing …** and **Saving …**. Long recordings are transcribed in blocks; the display names the block. At the top left the time runs along, with an estimate of the total duration from about five percent progress." },
      { art: "liste", punkte: [
        "**Cancel** stops a run. During speaker detection the cancellation only takes effect once that step has finished.",
        "**Edit** opens a finished transcript in the editor.",
        "How many runs work at the same time is set in the settings under **Simultaneous runs**. Several runs share the same graphics unit and together are no faster than one after another.",
      ] },
      { art: "hinweis", text: "Rule of thumb: on a Mac with Apple Silicon, one hour of recording takes a few minutes. Meanwhile you can work on other transcripts in the editor." },
    ],
  },
  {
    id: "bibliothek",
    titel: "Library",
    kurz: "All transcripts in one place: open, rename, import, delete.",
    bloecke: [
      { art: "p", text: "The **Human Editor** area first shows the library. Each row gives the name, duration, number of speakers and segments. One click opens the transcript in the editor. From the editor you get back with **Library** or a click on **Human Editor**." },
      { art: "bild", datei: "03-bibliothek", text: "The library in the Human Editor area." },
      { art: "liste", punkte: [
        "**Rename …** changes the name of the transcript. The name appears in exports and file names.",
        "**Delete …** moves the transcript to the library’s trash. Nothing is deleted for good; the `_papierkorb` folder is inside the library folder.",
        "**Show in Finder** opens the transcript’s folder.",
        "**Import transcript (VTT/CSV/enrich) …** takes in an existing transcript. The app then asks for the matching audio file; with Cancel you import without sound.",
      ] },
      { art: "p", text: "You can also open an enrich dossier (.enrich) by double-clicking it in Finder or by dragging it onto the app icon." },
      { art: "hinweis", text: "The app starts in the area and with the transcript you quit it in, at the same line." },
    ],
  },
  {
    id: "editor",
    titel: "Editor: text and turns",
    kurz: "Correct text, split, merge, insert and delete turns, set start times.",
    bloecke: [
      { art: "p", text: "The editor shows one segment per line: play button, start time, speaker, text and, on the right, the line actions. The active line is highlighted; during playback its time runs along in hundredths of a second. The same time is shown large at the top left and small at the bottom right." },
      { art: "bild", datei: "01-editor", text: "The editor: transcript on the left, side panel on the right, waveform and control bar at the bottom." },
      { art: "h", text: "Editing text" },
      { art: "p", text: "Click into the text and type. The app saves by itself; at the top you see **Saving …** and then **Saved** with the time of day. Before every save it stores the previous state in the transcript’s `history` folder (the last 30)." },
      { art: "h", text: "Splitting, inserting, merging and deleting turns" },
      { art: "tasten", zeilen: [
        ["[[Enter]] in the middle of the text", "Splits the segment at the cursor. The second part gets the estimated time of the split point."],
        ["[[Enter]] at the end of the text", "Creates a new, empty turn after it."],
        ["[[⌥]] [[Enter]]", "Interjection: creates a new turn with the time of the current playhead and puts the cursor into it. Also works in the middle of typing."],
        ["[[⌫]] at the start of the text", "Merges the segment with the previous one."],
        ["[[⌫]] in an empty field", "Deletes the segment."],
      ] },
      { art: "p", text: "You find the same actions as icons on the right of the line: **Split at cursor**, **Merge with previous**, **Delete segment** and **Memo for this line**." },
      { art: "bild", datei: "11-zeile", text: "A line: play button, start time, speaker, text, actions. The red dot indicates a memo." },
      { art: "h", text: "Editing the start time" },
      { art: "p", text: "Click the time of a line. Enter the new start time as hh:mm:ss.hh, for example 00:19:10.45, and confirm with [[Enter]]. [[Esc]] cancels. Shorter entries such as 19:10 or 75.5 work too. The line moves to the place that matches its new time." },
      { art: "h", text: "Changing the speaker of a line" },
      { art: "p", text: "A click on the speaker badge opens the menu. The most recently chosen speakers are at the top. **New speaker** creates a new person, **no speaker** removes the assignment." },
      { art: "h", text: "Text size" },
      { art: "p", text: "You set the size of the turn text in the settings under **Turn text size**." },
    ],
  },
  {
    id: "wiedergabe",
    titel: "Playback and waveform",
    kurz: "Play, jump, speed, loop, follow, zoom the waveform, video.",
    bloecke: [
      { art: "bild", datei: "09-wiedergabe", text: "Waveform with memo markers, below it the control bar: transport, speed, playback modes, and the time on the right." },
      { art: "h", text: "Control bar" },
      { art: "tabelle", kopf: ["Element", "Effect"], zeilen: [
        ["Transport", "Back 5 s, play or pause, forward 5 s."],
        ["Speed − value +", "**Slower** and **Faster** in steps from 0.75× to 2×. A click on the value restores 1×."],
        ["**Loop**", "Repeats the active segment until you switch the loop off."],
        ["**Follow**", "The list follows playback: the active line stays in the middle area of the window."],
      ] },
      { art: "p", text: "The play button at the front of each line plays **From here** and stops again on the second click." },
      { art: "h", text: "Waveform" },
      { art: "p", text: "The waveform shows the recording in the speakers’ colours. The vertical line is the playhead." },
      { art: "liste", punkte: [
        "Clicking or dragging sets the playhead.",
        "[[⌘]] + scroll wheel or the two-finger pinch gesture zooms around the pointer.",
        "Scrolling horizontally or [[⇧]] + scroll wheel moves the visible section.",
        "A double-click shows the whole recording again.",
        "During playback the visible section moves on as soon as the line reaches the edge.",
        "Red dots in the upper track are memos. Hovering over one shows the text, a click opens the memo.",
      ] },
      { art: "h", text: "Video" },
      { art: "p", text: "With a video source the picture plays muted next to the transcript; the sound comes from the transcript’s audio track. At 2× the picture freezes until you slow down." },
      { art: "p", text: "If the control bar says **No audio attached**, the transcript was imported without a sound file." },
    ],
  },
  {
    id: "sprecher",
    titel: "Speakers",
    kurz: "Name and colour speakers, listen to them, merge them and assign empty lines.",
    bloecke: [
      { art: "p", text: "The **Speakers** side panel lists all people in the transcript with the number of their segments. After transcription they are at first named by their number." },
      { art: "bild", datei: "05-sprecherfarbe", text: "Speakers side panel with the colour picker open." },
      { art: "liste", punkte: [
        "**Rename**: type the name into the field. It changes at once in all lines and exports.",
        "**Choose colour**: the coloured circle opens the palette. The colour applies to the badge, the waveform and the REFI-QDA export.",
        "**Sample**: plays a short excerpt of this voice so that you recognise it.",
        "**Merge into …**: attaches all segments of this person to another one. This helps when detection has split one voice into two.",
        "**Assign to all without speaker**: gives this person to all lines without a speaker.",
      ] },
      { art: "hinweis", text: "Speakers are entries of their own, not text in front of the line. Renaming and merging therefore never change the wording." },
    ],
  },
  {
    id: "suchen",
    titel: "Find and replace",
    kurz: "Find words, check them one by one and replace them, for example for pseudonyms.",
    bloecke: [
      { art: "p", text: "The **Find** side panel searches the text of the open transcript. Enter the term under **Find** and, if you want to replace, the new text under **Replace with**." },
      { art: "bild", datei: "04-suchen-ersetzen", text: "Find and replace: the matches are highlighted in the transcript." },
      { art: "liste", punkte: [
        "**Previous match** and **Next match** jump through the matches; the display gives the position, for instance 3 of 12.",
        "**Replace** replaces the current match, **Skip** leaves it as it is and moves on.",
        "**Replace all** replaces every match at once.",
        "**Ignore hyphenation** also finds forms written apart such as “coope- rative”.",
        "**Match case** distinguishes “House” and “house”.",
      ] },
      { art: "hinweis", text: "The search is literal: no translation, no word stems. For pseudonyms you therefore search for each spelling of a name separately." },
    ],
  },
  {
    id: "memos",
    titel: "Memos",
    kurz: "Your own notes per line, separate from the wording, exported to CSV and REFI-QDA.",
    bloecke: [
      { art: "p", text: "A memo is your note on a line: an observation, a query, a first thought for the analysis. It belongs to you and not to the wording." },
      { art: "bild", datei: "08-memo", text: "The memo of a line." },
      { art: "schritte", punkte: [
        "Click **Memo for this line** on the right of the line.",
        "Write the note and confirm with **Save** or [[⌘]] [[Enter]].",
        "**Delete memo** removes it again.",
      ] },
      { art: "p", text: "A line with a memo carries a red dot on the icon. In the waveform a red marker appears at its position." },
      { art: "tabelle", kopf: ["Export", "What happens to the memo"], zeilen: [
        ["CSV", "Separate column “Memo”. Several memos of one turn are separated by “ | ”."],
        ["REFI-QDA", "Memo on the coded passage; ATLAS.ti and MAXQDA show it there."],
        ["VTT, TXT", "Not included."],
        ["enrich dossier", "Not included yet."],
      ] },
    ],
  },
  {
    id: "metadaten",
    titel: "Metadata and Zotero",
    kurz: "Take title, date, interviewers and citekey from your local Zotero library.",
    bloecke: [
      { art: "p", text: "In the **Metadata** side panel you link a transcript to an item in your Zotero library. Title, date, interviewer and citekey are then included in the enrich dossier. Zotero is only read and never changed; it can stay open meanwhile." },
      { art: "h", text: "Enable once" },
      { art: "schritte", punkte: [
        "Open **Settings** and the **Zotero** card.",
        "Switch on **Allow reading the local Zotero database**.",
        "With **Change …**, choose the Zotero folder, usually `Zotero` in your home folder. The app needs this permission because it runs in a protected environment.",
        "If **Found** appears below, the database is readable.",
      ] },
      { art: "h", text: "Linking" },
      { art: "schritte", punkte: [
        "In the editor, open the **Metadata** side panel.",
        "Search by title, year, name or citekey.",
        "Select the item and click **Link**.",
        "Set the roles under **Which people go into the transcript?**.",
      ] },
      { art: "p", text: "**Reload** fetches changed details from Zotero, **Show in Zotero** opens the item there, **Unlink** removes the link." },
      { art: "hinweis", text: "The interviewed side (interviewee, guest, castMember) is not preselected. A pseudonymised transcript should not receive their name via Zotero." },
    ],
  },
  {
    id: "export",
    titel: "Export",
    kurz: "Which format for what: VTT, CSV, TXT, REFI-QDA and enrich dossier.",
    bloecke: [
      { art: "p", text: "At the top of the editor, **Export** opens the list of formats. After you choose, the app asks where to save. Exports are derived: the transcript in the library remains the source, and you can export again at any time." },
      { art: "bild", datei: "06-export", text: "The export formats in the editor." },
      { art: "tabelle", kopf: ["Format", "Content", "What for"], zeilen: [
        ["VTT", "Subtitles with times in milliseconds, speaker as a voice tag. Very short passages are joined into readable subtitles, long ones are split.", "Video players, editing software, re-import."],
        ["CSV", "One row per turn: Time-in, Time-out, Speaker, Text, Memo. Times as hh:mm:ss.hh.", "Spreadsheets, your own analysis, re-import."],
        ["TXT", "Running text, one paragraph per turn with the speaker’s name. No times.", "Reading, quoting, passing on."],
        ["**REFI-QDA for ATLAS.ti (.qdpx.zip)**", "Project file with text, sound, timestamps per utterance, speakers as codes, and memos.", "ATLAS.ti, MAXQDA, NVivo."],
        ["**REFI-QDA with video (.qdpx.zip)**", "As above, with the video file instead of the audio track. Only for video sources.", "Video analysis in QDA software."],
        ["**enrich dossier (.enrich)**", "Transcript, sound as MP3, Zotero metadata and a journal of who edited what and when.", "Further work in enrich, archive."],
      ] },
      { art: "hinweis", text: "The REFI-QDA export is a zip. Unpack it: inside are the project file `.qdpx` and a folder with the media file. Import the `.qdpx` file into your QDA software and leave the media folder next to it." },
    ],
  },
  {
    id: "einstellungen",
    titel: "Settings",
    kurz: "All the settings cards and what their options do.",
    bloecke: [
      { art: "bild", datei: "07-einstellungen", text: "The settings." },
      { art: "h", text: "Storage" },
      { art: "p", text: "The library folder. For each transcript a subfolder is created with transcript, audio and history. **Change …** chooses another folder; the app does not move existing transcripts when you do. **Show in Finder** opens the folder." },
      { art: "h", text: "Default options" },
      { art: "tabelle", kopf: ["Option", "Meaning"], zeilen: [
        ["**Whisper model**", "Default for new runs."],
        ["**Language**", "Default for the language of the recordings."],
        ["**Simultaneous runs**", "1 to 4. Recommended is **1 — one after another**."],
        ["**Interface language**", "Deutsch, English, Français, Italiano. Applies at once, also to this help window."],
        ["**Turn text size**", "Text size of the transcript text in the editor."],
      ] },
      { art: "h", text: "Identity in the dossier" },
      { art: "p", text: "**E-mail as user ID (optional)** writes your address into the journal of every enrich dossier you export. It leaves the computer only with that file. The **ID of this installation** is random and has no connection to a device or person; **Regenerate** assigns a new one." },
      { art: "h", text: "Zotero" },
      { art: "p", text: "Permission and folder of the Zotero database, see chapter “Metadata and Zotero”." },
      { art: "h", text: "Privacy" },
      { art: "p", text: "Sums up that everything stays local. **Privacy policy** opens the full text. **Open log** shows the app’s local log; it helps with troubleshooting and is never sent anywhere." },
      { art: "h", text: "Licenses, ResearchTranscript, Formats, BIAS.City" },
      { art: "p", text: "These cards name the included components and their licences (**All licences (list)**), the source code, the specifications of the export formats and the institute behind the app." },
      { art: "hinweis", text: "Light and dark follow the macOS setting under System Settings › Appearance." },
    ],
  },
  {
    id: "modelle",
    titel: "Your own models",
    kurz: "Use further whisper.cpp models, for example for Swiss German.",
    bloecke: [
      { art: "p", text: "The app ships with the large-v3-turbo model. You can use further whisper.cpp models in ggml format, for instance a fine-tune for Swiss German or a smaller, quantised variant." },
      { art: "schritte", punkte: [
        "Open **Settings**, card **Default options**, section **Your own models**.",
        "Click **Show in Finder** and put the file into this folder. The name must follow the pattern `ggml-….bin`.",
        "Click **Rescan**. The model appears in the **Whisper model** selection, marked as **own**.",
      ] },
      { art: "p", text: "A model of your own with the same name replaces the included one. The app itself never downloads models." },
      { art: "h", text: "If a model does not appear" },
      { art: "tabelle", kopf: ["Message", "What to do"], zeilen: [
        ["**still being copied**", "Wait until Finder has finished, then **Rescan**."],
        ["**not a whisper.cpp model (ggml)**", "The file has a different format, for example PyTorch or Core ML. You need the ggml version."],
        ["**incomplete (too small for a model)**", "The download was interrupted. Download the file again."],
        ["**stored in iCloud only**", "Download it in Finder via the cloud icon."],
        ["**ignored (name must be ggml-….bin)**", "Rename the file."],
      ] },
      { art: "hinweis", text: "What was used for transcription is recorded in each transcript’s journal. Your own models are not part of the list in the privacy sheet on the website; name them yourself in your documentation." },
    ],
  },
  {
    id: "tasten",
    titel: "Keyboard shortcuts",
    kurz: "All shortcuts of the editor, also for foot pedals.",
    bloecke: [
      { art: "p", text: "The editor has two layers: outside a text field, plain keys control playback. While you type, the keys belong to the text; the same commands are then on [[⌥]]. [[Esc]] leaves the text field." },
      { art: "h", text: "Playback" },
      { art: "tabelle", kopf: ["Command", "Outside the text", "While typing"], zeilen: [
        ["Play / pause", "[[Space]] or [[K]]", "[[⇧]] [[Space]], [[⌥]] [[Space]] or [[⌥]] [[K]]"],
        ["Back 5 s", "[[J]] or [[←]]", "[[⌥]] [[J]]"],
        ["Forward 5 s", "[[L]] or [[→]]", "[[⌥]] [[L]]"],
        ["Previous / next turn", "[[↑]] / [[↓]]", "[[⌥]] [[↑]] / [[⌥]] [[↓]] – the cursor moves along"],
        ["Previous / next turn (foot pedal)", "[[fn]] [[↑]] / [[fn]] [[↓]] (Page Up / Page Down)", "the same"],
        ["Loop on / off", "[[Ctrl]] [[L]]", "[[Ctrl]] [[L]]"],
        ["Next speed", "[[Ctrl]] [[X]]", "[[Ctrl]] [[X]]"],
      ] },
      { art: "h", text: "Text and turns" },
      { art: "tasten", zeilen: [
        ["[[Enter]]", "Split the segment at the cursor; at the end of the text: new turn."],
        ["[[⌥]] [[Enter]]", "Insert an interjection at the playhead."],
        ["[[⌫]] at the start of the text", "Merge with the previous segment."],
        ["[[⌫]] in an empty field", "Delete the segment."],
        ["[[Esc]]", "Leave the text field; after that the plain keys apply again."],
        ["[[⌘]] [[Z]] / [[⇧]] [[⌘]] [[Z]]", "Undo and redo in the text field."],
      ] },
      { art: "h", text: "More" },
      { art: "tasten", zeilen: [
        ["[[Enter]] / [[Esc]] in the time field", "Accept / discard the start time."],
        ["[[⌘]] [[Enter]] in the memo", "Save the memo."],
        ["[[⌘]] + scroll wheel on the waveform", "Zoom."],
        ["[[⇧]] + scroll wheel on the waveform", "Move the visible section."],
        ["Double-click on the waveform", "Show the whole recording."],
        ["[[⌘]] [[?]]", "Open this help."],
      ] },
      { art: "h", text: "Foot pedal" },
      { art: "p", text: "For a foot pedal that sends keys, use its software to assign Page Up and Page Down for changing turns and [[⇧]] [[Space]] for play and pause. These shortcuts also work while you are writing." },
    ],
  },
  {
    id: "daten",
    titel: "Data, privacy and troubleshooting",
    kurz: "Where your data is, what the app never does and what helps when there are problems.",
    bloecke: [
      { art: "h", text: "Where the data is" },
      { art: "p", text: "Everything is in the library folder, one subfolder per transcript:" },
      { art: "tabelle", kopf: ["File", "Content"], zeilen: [
        ["`transkript.json`", "The transcript: segments, speakers, memos, journal. The single source; exports are derived from it."],
        ["`audio.…`", "Copy of the recording, for videos also the video file."],
        ["`history/`", "The last 30 states before each save."],
        ["`wellenform.json`", "Cache of the waveform; recreated when needed."],
        ["`_papierkorb/`", "Deleted transcripts, in the library folder. You can empty it in Finder."],
      ] },
      { art: "hinweis", text: "For backups, back up the library folder. To move to another Mac, copy it and choose it there as the storage location." },
      { art: "h", text: "What the app never does" },
      { art: "liste", punkte: [
        "It transmits nothing: no recordings, no texts, no usage data.",
        "It does not download any models or program parts.",
        "It only reads folders you have selected and files you drop in.",
        "It does not change Zotero.",
      ] },
      { art: "h", text: "When something does not work" },
      { art: "tabelle", kopf: ["Observation", "What helps"], zeilen: [
        ["Banner “Processing has stopped responding …”", "**Restart app**. Your work is saved."],
        ["Run ends with **Failed**", "The message names the reason, for instance an unsupported video format. Convert the file to MP4 (H.264) or an audio format."],
        ["Wrong number of speakers", "Transcribe again with a fixed speaker count instead of **Automatic**, or merge speakers in the editor."],
        ["Many errors with dialect or technical language", "Choose a fixed **Language**; for Swiss German use a model of your own."],
        ["Zotero is not found", "In the settings, choose the Zotero folder again via **Change …**."],
        ["Something else", "**Settings › Privacy › Open log** and look at the last lines or send them along."],
      ] },
      { art: "p", text: "Questions and bug reports: bias.city/researchtranscript or the issues in the GitHub repository bias-city/ResearchTranscript." },
    ],
  },
];

export default kapitel;
