// Traduction française de de.ts : les ids des chapitres et les fichiers d'images doivent rester identiques.
import type { Kapitel } from "./typ";

const kapitel: Kapitel[] = [
  {
    id: "start",
    titel: "Premiers pas",
    kurz: "Ce que fait l'app, comment elle est organisée et comment obtenir une première transcription en cinq minutes.",
    bloecke: [
      { art: "p", text: "ResearchTranscript transforme un enregistrement en transcription avec locuteurs et repères temporels. Tout se passe sur ton Mac. Il n'y a ni compte, ni cloud, ni connexion réseau." },
      { art: "h", text: "Les trois espaces" },
      { art: "liste", punkte: [
        "**Transcription IA** : déposer des enregistrements, choisir le nombre de locuteurs, lancer la transcription.",
        "**Éditeur humain** : la bibliothèque de toutes les transcriptions. Un clic ouvre une transcription dans l'éditeur, où tu écoutes, corriges, nommes les locuteurs et exportes.",
        "**Réglages** : emplacement, options par défaut, Zotero, confidentialité et licences.",
      ] },
      { art: "h", text: "Le premier lancement" },
      { art: "p", text: "Au premier lancement, l'app demande sous **Choisir l'emplacement** où placer tes transcriptions. **Utiliser l'emplacement recommandé** crée le dossier dans tes documents. Avec **Choisir un autre dossier …**, tu prends ton propre dossier, par exemple sur un volume chiffré. L'app retient l'autorisation d'accès à ce dossier." },
      { art: "h", text: "Une transcription en cinq minutes" },
      { art: "schritte", punkte: [
        "Ouvre **Transcription IA** et dépose un fichier audio ou vidéo sur la zone **Dépose les fichiers audio ici**.",
        "Choisis pour ce fichier le nombre de personnes qui parlent.",
        "Clique sur **Lancer la transcription**. L'en-tête en haut à gauche affiche le temps écoulé et une estimation.",
        "Quand le traitement est **Terminé**, ouvre la transcription dans l'éditeur avec **Modifier**.",
        "Écoute avec [[Espace]], corrige le texte, nomme les locuteurs dans le panneau latéral **Locuteurs**.",
        "Choisis sous **Export** le format dont tu as besoin.",
      ] },
      { art: "bild", datei: "02-ai-transkript", text: "Transcription IA : en haut les options, en dessous les fichiers en attente du lancement et la liste des lots avec les traitements." },
      { art: "hinweis", text: "Cette fenêtre d'aide reste ouverte à côté de ton travail. Tu l'ouvres par le menu **Help**, avec [[⌘]] [[?]] ou avec le bouton **Aide** en bas à gauche de la fenêtre principale." },
    ],
  },
  {
    id: "transkribieren",
    titel: "Transcrire",
    kurz: "Mettre des fichiers en file, choisir le nombre de locuteurs et les options, suivre et annuler les traitements.",
    bloecke: [
      { art: "h", text: "Ajouter des fichiers" },
      { art: "p", text: "Dépose un ou plusieurs fichiers sur la zone **Dépose les fichiers audio ici**, ou clique dessus pour les choisir. Formats pris en charge : MP3, WAV, M4A, OGG et FLAC ; en vidéo, MP4 et MOV en H.264 ou HEVC. Pour une vidéo, l'app lit le son ; l'image défile ensuite en muet dans l'éditeur." },
      { art: "h", text: "Options" },
      { art: "tabelle", kopf: ["Option", "Signification"], zeilen: [
        ["**Modèle Whisper**", "Le modèle de reconnaissance vocale. large-v3-turbo est fourni. Tes propres modèles apparaissent ici dès qu'ils se trouvent dans le dossier des modèles (chapitre « Tes propres modèles »)."],
        ["**Langue**", "Langue de l'enregistrement : de, en, fr, it, es ou auto. Une langue fixe est plus fiable que la détection automatique."],
        ["**Locuteurs** · **Valeur par défaut pour les nouveaux fichiers**", "Nombre de locuteurs repris par un fichier ajouté seul : 1 à 6 ou **Automatique**. Avec 1, la détection des locuteurs est omise."],
        ["**Séparation**", "Rigueur avec laquelle les voix sont distinguées : **Souple**, **Normale**, **Stricte**, **Très stricte**. Une séparation stricte répartit plutôt des voix semblables sur deux locuteurs, une séparation souple les réunit plutôt. L'effet se voit surtout avec **Automatique**."],
      ] },
      { art: "h", text: "Prêt à démarrer : nombre de locuteurs par fichier" },
      { art: "p", text: "Chaque fichier de la liste **Prêt à démarrer** a son propre nombre de locuteurs. Si tu déposes plusieurs fichiers à la fois, tu dois le choisir pour chacun. Tant qu'un fichier affiche **Choisir le nombre de locuteurs**, aucun traitement ne démarre. Ce nombre influence fortement le résultat et figure ensuite dans le journal de la transcription. **Retirer de la liste** enlève un fichier. La liste est conservée après un redémarrage de l'app." },
      { art: "h", text: "Suivre les traitements" },
      { art: "p", text: "**Lancer la transcription** envoie tous les fichiers en attente dans la **Liste des lots**. Un traitement passe par les étapes **Conversion audio …**, **Détection des locuteurs …**, **Transcription …** et **Enregistrement …**. Les longs enregistrements sont transcrits par blocs ; l'affichage indique le bloc en cours. En haut à gauche, le temps défile, avec une estimation de la durée totale à partir d'environ cinq pour cent de progression." },
      { art: "liste", punkte: [
        "**Annuler** arrête un traitement. Pendant la détection des locuteurs, l'annulation ne prend effet qu'à la fin de cette étape.",
        "**Modifier** ouvre une transcription terminée dans l'éditeur.",
        "Le nombre de traitements menés en parallèle se règle dans les réglages, sous **Exécutions simultanées**. Plusieurs traitements se partagent le même processeur graphique et ne sont pas plus rapides ensemble que l'un après l'autre.",
      ] },
      { art: "hinweis", text: "Ordre de grandeur : sur un Mac avec Apple Silicon, une heure d'enregistrement demande quelques minutes. Pendant ce temps, tu peux travailler sur d'autres transcriptions dans l'éditeur." },
    ],
  },
  {
    id: "bibliothek",
    titel: "Bibliothèque",
    kurz: "Toutes les transcriptions au même endroit : ouvrir, renommer, importer, supprimer.",
    bloecke: [
      { art: "p", text: "L'espace **Éditeur humain** affiche d'abord la bibliothèque. Chaque ligne indique le nom, la durée, le nombre de locuteurs et de segments. Un clic ouvre la transcription dans l'éditeur. Depuis l'éditeur, tu reviens avec **Bibliothèque** ou par un clic sur **Éditeur humain**." },
      { art: "bild", datei: "03-bibliothek", text: "La bibliothèque dans l'espace Éditeur humain." },
      { art: "liste", punkte: [
        "**Renommer …** change le nom de la transcription. Ce nom apparaît dans les exports et les noms de fichiers.",
        "**Supprimer …** déplace la transcription dans la corbeille de la bibliothèque. Rien n'est supprimé définitivement ; le dossier `_papierkorb` se trouve dans le dossier de la bibliothèque.",
        "**Afficher dans le Finder** ouvre le dossier de la transcription.",
        "**Importer une transcription (VTT/CSV/enrich) …** reprend une transcription existante. L'app demande ensuite le fichier audio correspondant ; avec Annuler, tu importes sans le son.",
      ] },
      { art: "p", text: "Un dossier enrich (.enrich) s'ouvre aussi par un double-clic dans le Finder ou en le glissant sur l'icône de l'app." },
      { art: "hinweis", text: "L'app démarre dans l'espace et la transcription où tu l'as quittée, à la même ligne." },
    ],
  },
  {
    id: "editor",
    titel: "Éditeur : texte et tours",
    kurz: "Corriger le texte, scinder, fusionner, insérer et supprimer des tours, régler les temps de début.",
    bloecke: [
      { art: "p", text: "L'éditeur affiche un segment par ligne : bouton de lecture, temps de début, locuteur, texte et, à droite, les actions de la ligne. La ligne active est mise en évidence ; pendant la lecture, son temps défile au centième de seconde. Le même temps figure en grand en haut à gauche et en petit en bas à droite." },
      { art: "bild", datei: "01-editor", text: "L'éditeur : la transcription à gauche, le panneau latéral à droite, en bas la forme d'onde et la barre de commande." },
      { art: "h", text: "Modifier le texte" },
      { art: "p", text: "Clique dans le texte et écris. L'app enregistre d'elle-même ; en haut s'affiche **Enregistrement …**, puis **Enregistré** avec l'heure. Avant chaque enregistrement, elle dépose l'état précédent dans le dossier `history` de la transcription (les 30 derniers)." },
      { art: "h", text: "Scinder, insérer, fusionner, supprimer des tours" },
      { art: "tasten", zeilen: [
        ["[[Entrée]] au milieu du texte", "Scinde le segment au curseur. La seconde partie reçoit le temps estimé du point de coupe."],
        ["[[Entrée]] en fin de texte", "Crée à la suite un nouveau tour vide."],
        ["[[⌥]] [[Entrée]]", "Intervention : crée un nouveau tour au temps de la position de lecture actuelle et y place le curseur. Fonctionne aussi en pleine saisie."],
        ["[[⌫]] en début de texte", "Fusionne le segment avec le précédent."],
        ["[[⌫]] dans un champ vide", "Supprime le segment."],
      ] },
      { art: "p", text: "Les mêmes actions existent sous forme d'icônes à droite de la ligne : **Scinder au curseur**, **Fusionner avec le précédent**, **Supprimer le segment** et **Mémo pour cette ligne**." },
      { art: "bild", datei: "11-zeile", text: "Une ligne : bouton de lecture, temps de début, locuteur, texte, actions. Le point rouge signale un mémo." },
      { art: "h", text: "Modifier le temps de début" },
      { art: "p", text: "Clique sur le temps d'une ligne. Saisis le nouveau temps de début au format hh:mm:ss.hh, par exemple 00:19:10.45, et valide avec [[Entrée]]. [[Esc]] annule. Des saisies plus courtes comme 19:10 ou 75.5 fonctionnent aussi. La ligne se range selon son nouveau temps." },
      { art: "h", text: "Changer le locuteur d'une ligne" },
      { art: "p", text: "Un clic sur l'étiquette du locuteur ouvre le menu. Les locuteurs choisis en dernier figurent en haut. **Nouveau locuteur** crée une nouvelle personne, **sans locuteur** retire l'attribution." },
      { art: "h", text: "Taille du texte" },
      { art: "p", text: "La taille du texte des tours se règle dans les réglages, sous **Taille du texte des tours**." },
    ],
  },
  {
    id: "wiedergabe",
    titel: "Lecture et forme d'onde",
    kurz: "Lire, sauter, vitesse, boucle, suivi, zoom dans la forme d'onde, vidéo.",
    bloecke: [
      { art: "bild", datei: "09-wiedergabe", text: "Forme d'onde avec les marqueurs de mémos, en dessous la barre de commande : transport, vitesse, modes de lecture, à droite le temps." },
      { art: "h", text: "Barre de commande" },
      { art: "tabelle", kopf: ["Élément", "Effet"], zeilen: [
        ["Transport", "5 s en arrière, lecture ou pause, 5 s en avant."],
        ["Vitesse − valeur +", "**Plus lent** et **Plus rapide** par paliers de 0,75× à 2×. Un clic sur la valeur rétablit 1×."],
        ["**Boucle**", "Répète le segment actif jusqu'à ce que tu désactives la boucle."],
        ["**Suivre**", "La liste suit la lecture : la ligne active reste dans la zone centrale de la fenêtre."],
      ] },
      { art: "p", text: "Le bouton de lecture au début de chaque ligne lit **À partir d'ici** et arrête la lecture au second clic." },
      { art: "h", text: "Forme d'onde" },
      { art: "p", text: "La forme d'onde montre l'enregistrement aux couleurs des locuteurs. La ligne verticale est la position de lecture." },
      { art: "liste", punkte: [
        "Cliquer ou faire glisser place la position de lecture.",
        "[[⌘]] + molette ou le geste d'écartement à deux doigts zoome autour du pointeur.",
        "Le défilement horizontal ou [[⇧]] + molette déplace la portion affichée.",
        "Un double-clic affiche de nouveau tout l'enregistrement.",
        "Pendant la lecture, la portion affichée avance dès que la ligne atteint le bord.",
        "Les points rouges de la piste supérieure sont des mémos. Le pointeur placé dessus affiche le texte, un clic ouvre le mémo.",
      ] },
      { art: "h", text: "Vidéo" },
      { art: "p", text: "Avec une source vidéo, l'image défile en muet à côté de la transcription ; le son vient de la piste audio de la transcription. À 2×, l'image reste figée jusqu'à ce que tu ralentisses." },
      { art: "p", text: "Si la barre de commande affiche **Aucun audio associé**, la transcription a été importée sans fichier audio." },
    ],
  },
  {
    id: "sprecher",
    titel: "Locuteurs",
    kurz: "Nommer les locuteurs, leur donner une couleur, les écouter, les fusionner et attribuer les lignes sans locuteur.",
    bloecke: [
      { art: "p", text: "Le panneau latéral **Locuteurs** liste toutes les personnes de la transcription avec le nombre de leurs segments. Après la transcription, elles portent d'abord leur numéro pour nom." },
      { art: "bild", datei: "05-sprecherfarbe", text: "Panneau latéral Locuteurs avec le choix de couleur ouvert." },
      { art: "liste", punkte: [
        "**Renommer** : écris le nom dans le champ. Il change aussitôt dans toutes les lignes et tous les exports.",
        "**Choisir la couleur** : le cercle coloré ouvre la palette. La couleur vaut pour l'étiquette, la forme d'onde et l'export REFI-QDA.",
        "**Extrait** : lit un court passage de cette voix pour que tu la reconnaisses.",
        "**Fusionner dans …** : rattache tous les segments de cette personne à une autre. Utile quand la détection a réparti une voix sur deux locuteurs.",
        "**Attribuer à tous sans locuteur** : donne cette personne à toutes les lignes sans locuteur.",
      ] },
      { art: "hinweis", text: "Les locuteurs sont des entrées à part, pas du texte placé devant la ligne. Renommer et fusionner ne modifient donc jamais le verbatim." },
    ],
  },
  {
    id: "suchen",
    titel: "Rechercher et remplacer",
    kurz: "Trouver des mots, les vérifier un à un et les remplacer, par exemple pour des pseudonymes.",
    bloecke: [
      { art: "p", text: "Le panneau latéral **Rechercher** parcourt le texte de la transcription ouverte. Saisis le terme sous **Rechercher** et, si tu veux remplacer, le nouveau texte sous **Remplacer par**." },
      { art: "bild", datei: "04-suchen-ersetzen", text: "Rechercher et remplacer : les résultats sont surlignés dans la transcription." },
      { art: "liste", punkte: [
        "**Résultat précédent** et **Résultat suivant** passent d'une occurrence à l'autre ; l'affichage indique la position, par exemple 3 sur 12.",
        "**Remplacer** remplace le résultat actuel, **Ignorer** le laisse tel quel et passe au suivant.",
        "**Tout remplacer** remplace tous les résultats d'un coup.",
        "**Ignorer la césure** trouve aussi les formes écrites en deux parties comme « coopé- rative ».",
        "**Respecter la casse** distingue « Maison » et « maison ».",
      ] },
      { art: "hinweis", text: "La recherche est littérale : pas de traduction, pas de formes fléchies. Pour des pseudonymes, tu cherches donc chaque graphie d'un nom séparément." },
    ],
  },
  {
    id: "memos",
    titel: "Mémos",
    kurz: "Tes notes par ligne, séparées du verbatim, avec export vers CSV et REFI-QDA.",
    bloecke: [
      { art: "p", text: "Un mémo est ta note sur une ligne : une observation, une question à reposer, une première idée pour l'analyse. Il t'appartient et ne fait pas partie du verbatim." },
      { art: "bild", datei: "08-memo", text: "Le mémo d'une ligne." },
      { art: "schritte", punkte: [
        "Clique à droite de la ligne sur **Mémo pour cette ligne**.",
        "Écris la note et valide avec **Enregistrer** ou [[⌘]] [[Entrée]].",
        "**Supprimer le mémo** l'enlève.",
      ] },
      { art: "p", text: "Une ligne avec mémo porte un point rouge sur l'icône. Dans la forme d'onde, un marqueur rouge apparaît à son emplacement." },
      { art: "tabelle", kopf: ["Export", "Ce que devient le mémo"], zeilen: [
        ["CSV", "Colonne dédiée « Memo ». Plusieurs mémos d'un même tour sont séparés par « | »."],
        ["REFI-QDA", "Mémo sur le passage codé ; ATLAS.ti et MAXQDA l'y affichent."],
        ["VTT, TXT", "Non inclus."],
        ["Dossier enrich", "Pas encore inclus."],
      ] },
    ],
  },
  {
    id: "metadaten",
    titel: "Métadonnées et Zotero",
    kurz: "Reprendre le titre, la date, les personnes qui mènent l'entretien et le citekey depuis la bibliothèque Zotero locale.",
    bloecke: [
      { art: "p", text: "Dans le panneau latéral **Métadonnées**, tu lies une transcription à une entrée de ta bibliothèque Zotero. Le titre, la date, l'intervieweur·euse et le citekey figurent alors dans le dossier enrich. Zotero est seulement lu, jamais modifié ; il peut rester ouvert." },
      { art: "h", text: "Activer une fois" },
      { art: "schritte", punkte: [
        "Ouvre **Réglages** et la carte **Zotero**.",
        "Active **Autoriser la lecture de la base Zotero locale**.",
        "Choisis avec **Modifier …** le dossier Zotero, en général `Zotero` dans ton dossier utilisateur. L'app a besoin de cette autorisation parce qu'elle fonctionne dans un environnement protégé.",
        "Si **Trouvé** s'affiche en dessous, la base de données est lisible.",
      ] },
      { art: "h", text: "Lier" },
      { art: "schritte", punkte: [
        "Ouvre dans l'éditeur le panneau latéral **Métadonnées**.",
        "Cherche par titre, année, nom ou citekey.",
        "Choisis l'entrée et clique sur **Lier**.",
        "Définis les rôles sous **Quelles personnes entrent dans la transcription ?**.",
      ] },
      { art: "p", text: "**Recharger** reprend les données modifiées dans Zotero, **Afficher dans Zotero** y ouvre l'entrée, **Dissocier** défait le lien." },
      { art: "hinweis", text: "La partie interviewée (interviewee, guest, castMember) n'est pas présélectionnée. Une transcription pseudonymisée ne doit pas recevoir son nom par Zotero." },
    ],
  },
  {
    id: "export",
    titel: "Export",
    kurz: "Quel format pour quel usage : VTT, CSV, TXT, REFI-QDA et dossier enrich.",
    bloecke: [
      { art: "p", text: "En haut de l'éditeur, **Export** ouvre la liste des formats. Après le choix, l'app demande l'emplacement d'enregistrement. Les exports sont dérivés : la transcription de la bibliothèque reste la source, tu peux réexporter à tout moment." },
      { art: "bild", datei: "06-export", text: "Les formats d'export dans l'éditeur." },
      { art: "tabelle", kopf: ["Format", "Contenu", "Usage"], zeilen: [
        ["VTT", "Sous-titres avec temps en millisecondes, locuteur en voice tag. Les passages très courts sont réunis en sous-titres lisibles, les longs sont divisés.", "Lecteurs vidéo, logiciels de montage, réimport."],
        ["CSV", "Une ligne par tour : Time-in, Time-out, Speaker, Text, Memo. Temps au format hh:mm:ss.hh.", "Tableurs, analyse personnelle, réimport."],
        ["TXT", "Texte continu, un paragraphe par tour avec le nom du locuteur. Sans temps.", "Lire, citer, transmettre."],
        ["Markdown (.md), Word (.docx)", "Version de lecture avec en-tête (durée, locuteurs ; avec un lien Zotero : date, personnes, citekey), locuteur et temps de début pour chaque tour, mémos en bloc de citation.", "Lire, commenter, déposer dans une archive."],
        ["**REFI-QDA pour ATLAS.ti (.qdpx.zip)**", "Fichier de projet avec texte, son, repères temporels par énoncé, locuteurs sous forme de codes et mémos.", "ATLAS.ti, MAXQDA, NVivo."],
        ["**REFI-QDA avec vidéo (.qdpx.zip)**", "Comme ci-dessus, avec le fichier vidéo à la place de la piste audio. Uniquement pour les sources vidéo.", "Analyse vidéo dans un logiciel QDA."],
        ["**Dossier enrich (.enrich)**", "Transcription, son en MP3, métadonnées Zotero et un journal de qui a modifié quoi et quand.", "Poursuite du travail dans enrich, archive."],
      ] },
      { art: "p", text: "Sous le trait de séparation se trouve **Paquet de documentation (.zip) …**. Il documente comment cette transcription est née ; plus de détails dans le chapitre « Documentation pour la recherche »." },
      { art: "hinweis", text: "L'export REFI-QDA est un zip. Décompresse-le : il contient le fichier de projet `.qdpx` et un dossier avec le média. Importe le fichier `.qdpx` dans ton logiciel QDA et laisse le dossier du média à côté." },
    ],
  },
  {
    id: "dokumentation",
    titel: "Documentation pour la recherche",
    kurz: "Le paquet de documentation d'une transcription : neuf courts documents Word pour la partie méthodes, la protection des données et le dépôt des données, générés à partir des valeurs réelles.",
    bloecke: [
      { art: "p", text: "L'app sait quel modèle a tourné, quand la transcription a eu lieu et à quel point tu as modifié la transcription brute. Elle en tire les documents dont tu as besoin pour la partie méthodes, la protection des données et l'archive de données. Les indications portent sur une transcription à la fois. Ce que toi seul·e sais reste un champ ouvert `[ … ]` : qui a corrigé, selon quelles règles, avec quel consentement." },
      { art: "h", text: "Comment procéder" },
      { art: "schritte", punkte: [
        "Ouvre la transcription dans l'éditeur et choisis, sous **Export**, l'entrée **Paquet de documentation (.zip) …**.",
        "Choisis l'emplacement d'enregistrement. Le zip contient de courts documents Word répartis dans trois dossiers et un fichier de citation, mais ni transcription ni enregistrement.",
        "Remplis les champs ouverts `[ … ]` et vérifie chaque proposition tirée de Zotero.",
      ] },
      { art: "h", text: "Ce que contient le paquet" },
      { art: "tabelle", kopf: ["Dossier", "Document", "Usage"], zeilen: [
        ["", "`LISEZMOI`", "Guide du paquet et remarques à lire avant une transmission."],
        ["`1-methodes`", "Protocole de transcription", "Comment la transcription a été produite : application et modèle du traitement, révision manuelle selon le journal, mesure d'intervention, fichiers avec sommes de contrôle."],
        ["`1-methodes`", "Paragraphe pour la partie méthodes", "Un paragraphe pour la partie méthodes, en version courte et en version détaillée, avec les champs que toi seul·e connais."],
        ["`2-protection-des-donnees`", "Faits sur l'app", "Ce que l'app fait et ne fait pas, quelles mesures de protection elle offre, où se trouvent les données, ce que contiennent les exports."],
        ["`2-protection-des-donnees`", "Indications du responsable du traitement", "Formulaire pour ce que seul le responsable du traitement sait, et une liste pour retirer entièrement un entretien."],
        ["`3-depot-des-donnees`", "Fiche du jeu de données", "Champs dans l'ordre du formulaire de Zenodo, une fois par jeu de données."],
        ["`3-depot-des-donnees`", "Fiche de l'entretien", "Indications sur cet entretien précis et remarques sur les formats de fichiers."],
        ["`3-depot-des-donnees`", "Liste de contrôle éthique", "Points de contrôle avant une publication."],
        ["`3-depot-des-donnees`", "Entrepôts et exigences", "Zenodo, SWISSUbase, Qualiservice et d'autres, avec les exigences du FNS et de la DFG."],
        ["`citer`", "`researchtranscript.bib`", "ResearchTranscript comme entrée « Logiciel », plus les programmes et les modèles. Dans Zotero, par Fichier › Importer."],
      ] },
      { art: "h", text: "La mesure d'intervention" },
      { art: "p", text: "Le protocole indique deux mesures. La première provient du journal et est toujours disponible : la part des segments dont tu as modifié le texte ou le locuteur. La seconde se mesure par rapport à l'état initial automatique, que l'app conserve depuis la version 0.6.0 à la création d'une transcription :" },
      { art: "liste", punkte: [
        "Taux de correction au niveau des mots : mots remplacés, supprimés et insérés, divisés par les mots de la version finale. Calculé comme le taux d'erreur de mots (WER), avec la version finale comme référence. Une fois normalisé (en minuscules, sans ponctuation) et une fois orthographique (majuscules, minuscules et ponctuation comptent).",
        "Temps de parole réattribué : part du temps de parole dont tu as changé le locuteur. S'y ajoute une lecture dans laquelle la fusion de deux voix ne compte pas.",
      ] },
      { art: "hinweis", text: "C'est une mesure d'intervention, et non une mesure d'exactitude. Le taux comprend aussi la pseudonymisation et le lissage, et il ne saisit pas les erreurs que personne n'a remarquées. Pour les transcriptions issues de versions plus anciennes, l'état initial manque ; le protocole et le paragraphe indiquent alors la mesure tirée du journal." },
      { art: "h", text: "Publier des données d'entretien" },
      { art: "liste", punkte: [
        "L'enregistrement audio contient la voix et constitue une donnée personnelle. Il n'a pas sa place dans un entrepôt en accès ouvert.",
        "Pseudonymisé ne veut pas dire anonyme. Pour des données sensibles, une archive spécialisée avec contrôle d'accès convient mieux que Zenodo.",
        "Les métadonnées sont toujours publiques : aucun nom dans le titre, la description, les mots-clés et les noms de fichiers.",
        "Les personnes interrogées n'apparaissent jamais comme auteurs. Depuis Zotero, l'app ne propose que des personnes qui n'appartiennent pas à la partie interviewée.",
      ] },
    ],
  },
  {
    id: "einstellungen",
    titel: "Réglages",
    kurz: "Toutes les cartes des réglages et l'effet de leurs options.",
    bloecke: [
      { art: "bild", datei: "07-einstellungen", text: "Les réglages." },
      { art: "h", text: "Emplacement" },
      { art: "p", text: "Le dossier de la bibliothèque. Chaque transcription reçoit un sous-dossier avec la transcription, l'audio et l'historique. **Modifier …** choisit un autre dossier ; l'app ne déplace pas les transcriptions existantes. **Afficher dans le Finder** ouvre le dossier." },
      { art: "h", text: "Options par défaut" },
      { art: "tabelle", kopf: ["Option", "Signification"], zeilen: [
        ["**Modèle Whisper**", "Valeur par défaut pour les nouveaux traitements."],
        ["**Langue**", "Valeur par défaut pour la langue des enregistrements."],
        ["**Exécutions simultanées**", "1 à 4. Recommandé : **1 — l'un après l'autre**."],
        ["**Langue de l'interface**", "Deutsch, English, Français, Italiano. S'applique aussitôt, y compris à cette fenêtre d'aide."],
        ["**Taille du texte des tours**", "Taille du texte de la transcription dans l'éditeur."],
      ] },
      { art: "h", text: "Identité dans le dossier" },
      { art: "p", text: "**E-mail comme identifiant (facultatif)** écrit ton adresse dans le journal de chaque dossier enrich que tu exportes. Elle ne quitte l'ordinateur qu'avec ce fichier. L'**Identifiant de cette installation** est aléatoire, sans lien avec l'appareil ni la personne ; **Régénérer** en attribue un nouveau." },
      { art: "h", text: "Zotero" },
      { art: "p", text: "Activation et dossier de la base de données Zotero, voir le chapitre « Métadonnées et Zotero »." },
      { art: "h", text: "Confidentialité" },
      { art: "p", text: "Résume le fait que tout reste en local. **Politique de confidentialité** ouvre le texte complet. **Ouvrir le journal** affiche le journal local de l'app ; il aide à trouver la cause d'un problème et n'est jamais envoyé." },
      { art: "h", text: "Licences, ResearchTranscript, Formats, BIAS.City" },
      { art: "p", text: "Ces cartes indiquent les composants fournis et leurs licences (**Toutes les licences (liste)**), le code source, les spécifications des formats d'export et l'institut à l'origine de l'app." },
      { art: "hinweis", text: "Les modes clair et sombre suivent le réglage de macOS sous Réglages Système › Apparence." },
    ],
  },
  {
    id: "modelle",
    titel: "Tes propres modèles",
    kurz: "Utiliser d'autres modèles whisper.cpp, par exemple pour le suisse allemand.",
    bloecke: [
      { art: "p", text: "L'app fournit le modèle large-v3-turbo. Tu peux utiliser d'autres modèles whisper.cpp au format ggml, par exemple un modèle affiné pour le suisse allemand ou une variante plus petite, quantifiée." },
      { art: "schritte", punkte: [
        "Ouvre **Réglages**, carte **Options par défaut**, section **Tes propres modèles**.",
        "Clique sur **Afficher dans le Finder** et place le fichier dans ce dossier. Le nom doit suivre le modèle `ggml-….bin`.",
        "Clique sur **Relire**. Le modèle apparaît dans la sélection **Modèle Whisper**, marqué **perso**.",
      ] },
      { art: "p", text: "Un modèle personnel portant le même nom remplace celui qui est fourni. L'app ne télécharge jamais de modèles elle-même." },
      { art: "h", text: "Si un modèle n'apparaît pas" },
      { art: "tabelle", kopf: ["Message", "Que faire"], zeilen: [
        ["**copie en cours**", "Attendre que le Finder ait terminé, puis **Relire**."],
        ["**pas un modèle whisper.cpp (ggml)**", "Le fichier est dans un autre format, par exemple PyTorch ou Core ML. Il te faut la version ggml."],
        ["**incomplet (trop petit pour un modèle)**", "Le téléchargement a été interrompu. Télécharge de nouveau le fichier."],
        ["**seulement dans iCloud**", "Le télécharger dans le Finder avec l'icône nuage."],
        ["**ignoré (le nom doit être ggml-….bin)**", "Renommer le fichier."],
      ] },
      { art: "hinweis", text: "Le journal de chaque transcription indique le modèle utilisé. Tes propres modèles ne font pas partie de la liste de la fiche de protection des données du site web ; mentionne-les toi-même dans ta documentation." },
    ],
  },
  {
    id: "tasten",
    titel: "Raccourcis clavier",
    kurz: "Tous les raccourcis de l'éditeur, aussi pour les pédales.",
    bloecke: [
      { art: "p", text: "L'éditeur a deux niveaux : hors d'un champ de texte, de simples touches commandent la lecture. Pendant la saisie, les touches appartiennent au texte ; les mêmes commandes se trouvent alors sur [[⌥]]. [[Esc]] quitte le champ de texte." },
      { art: "h", text: "Lecture" },
      { art: "tabelle", kopf: ["Commande", "Hors du texte", "Pendant la saisie"], zeilen: [
        ["Lecture / pause", "[[Espace]] ou [[K]]", "[[⇧]] [[Espace]], [[⌥]] [[Espace]] ou [[⌥]] [[K]]"],
        ["5 s en arrière", "[[J]] ou [[←]]", "[[⌥]] [[J]]"],
        ["5 s en avant", "[[L]] ou [[→]]", "[[⌥]] [[L]]"],
        ["Tour précédent / suivant", "[[↑]] / [[↓]]", "[[⌥]] [[↑]] / [[⌥]] [[↓]] – le curseur suit"],
        ["Tour précédent / suivant (pédale)", "[[fn]] [[↑]] / [[fn]] [[↓]] (Page précédente / Page suivante)", "idem"],
        ["Boucle activée / désactivée", "[[Ctrl]] [[L]]", "[[Ctrl]] [[L]]"],
        ["Vitesse suivante", "[[Ctrl]] [[X]]", "[[Ctrl]] [[X]]"],
      ] },
      { art: "h", text: "Texte et tours" },
      { art: "tasten", zeilen: [
        ["[[Entrée]]", "Scinder le segment au curseur ; en fin de texte : nouveau tour."],
        ["[[⌥]] [[Entrée]]", "Insérer une intervention à la position de lecture."],
        ["[[⌫]] en début de texte", "Fusionner avec le segment précédent."],
        ["[[⌫]] dans un champ vide", "Supprimer le segment."],
        ["[[Esc]]", "Quitter le champ de texte ; les touches simples s'appliquent de nouveau."],
        ["[[⌘]] [[Z]] / [[⇧]] [[⌘]] [[Z]]", "Annuler et rétablir dans le champ de texte."],
      ] },
      { art: "h", text: "Autres" },
      { art: "tasten", zeilen: [
        ["[[Entrée]] / [[Esc]] dans le champ du temps", "Valider / abandonner le temps de début."],
        ["[[⌘]] [[Entrée]] dans le mémo", "Enregistrer le mémo."],
        ["[[⌘]] + molette sur la forme d'onde", "Zoomer."],
        ["[[⇧]] + molette sur la forme d'onde", "Déplacer la portion affichée."],
        ["Double-clic sur la forme d'onde", "Afficher tout l'enregistrement."],
        ["[[⌘]] [[?]]", "Ouvrir cette aide."],
      ] },
      { art: "h", text: "Pédale" },
      { art: "p", text: "Une pédale qui envoie des touches se configure dans son logiciel avec Page précédente et Page suivante pour changer de tour, et avec [[⇧]] [[Espace]] pour la lecture et la pause. Ces raccourcis agissent aussi pendant que tu écris." },
    ],
  },
  {
    id: "daten",
    titel: "Données, confidentialité et dépannage",
    kurz: "Où se trouvent tes données, ce que l'app ne fait jamais et ce qui aide en cas de problème.",
    bloecke: [
      { art: "h", text: "Où se trouvent les données" },
      { art: "p", text: "Tout se trouve dans le dossier de la bibliothèque, un sous-dossier par transcription :" },
      { art: "tabelle", kopf: ["Fichier", "Contenu"], zeilen: [
        ["`transkript.json`", "La transcription : segments, locuteurs, mémos, journal. La source unique ; les exports en sont dérivés."],
        ["`audio.…`", "Copie de l'enregistrement ; pour une vidéo, le fichier vidéo en plus."],
        ["`ausgang.json`", "L'état initial automatique, inchangé. C'est par rapport à lui que l'app calcule la mesure d'intervention."],
        ["`history/`", "Les 30 derniers états, déposés avant chaque enregistrement."],
        ["`wellenform.json`", "Cache de la forme d'onde ; il est recréé au besoin."],
        ["`_papierkorb/`", "Transcriptions supprimées, dans le dossier de la bibliothèque. Tu peux le vider dans le Finder."],
      ] },
      { art: "hinweis", text: "Pour tes sauvegardes, sauvegarde le dossier de la bibliothèque. Pour passer à un autre Mac, copie-le et choisis-le là-bas comme emplacement." },
      { art: "hinweis", text: "Si tu pseudonymises dans l'éditeur, cela modifie la version finale. `ausgang.json`, `history/` et l'enregistrement contiennent toujours le texte d'origine avec les noms réels. Ne transmets pas ces fichiers, et supprime-les dans le Finder si ton projet l'exige. Après cela, plus aucune mesure d'intervention ne peut être calculée." },
      { art: "h", text: "Ce que l'app ne fait jamais" },
      { art: "liste", punkte: [
        "Elle ne transmet rien : ni enregistrements, ni textes, ni données d'utilisation.",
        "Elle ne télécharge ni modèles ni composants du programme.",
        "Elle ne lit que les dossiers que tu as choisis et les fichiers que tu y déposes.",
        "Elle ne modifie pas Zotero.",
      ] },
      { art: "h", text: "Si quelque chose ne fonctionne pas" },
      { art: "tabelle", kopf: ["Observation", "Ce qui aide"], zeilen: [
        ["Bandeau « Le traitement ne répond plus … »", "**Redémarrer l'app**. Le travail en cours est enregistré."],
        ["Un traitement se termine par **Échec**", "Le message indique la raison, par exemple un format vidéo non pris en charge. Convertis le fichier en MP4 (H.264) ou dans un format audio."],
        ["Nombre de locuteurs incorrect", "Transcris de nouveau avec un nombre fixe de locuteurs au lieu de **Automatique**, ou fusionne des locuteurs dans l'éditeur."],
        ["Beaucoup d'erreurs avec un dialecte ou un langage spécialisé", "Choisir une **Langue** fixe ; pour le suisse allemand, utiliser un modèle personnel."],
        ["Zotero est introuvable", "Dans les réglages, choisir de nouveau le dossier Zotero avec **Modifier …**."],
        ["Autre chose", "**Réglages › Confidentialité › Ouvrir le journal**, puis regarder les dernières lignes ou les joindre à ton message."],
      ] },
      { art: "p", text: "Questions et rapports d'erreur : bias.city/researchtranscript ou les issues du dépôt GitHub bias-city/ResearchTranscript." },
    ],
  },
];

export default kapitel;
