// Traduzione italiana di de.ts. Gli id dei capitoli e i file immagine devono restare identici; le etichette in **…** corrispondono alla lettera ai valori it di lib/i18n.ts.
import type { Kapitel } from "./typ";

const kapitel: Kapitel[] = [
  {
    id: "start",
    titel: "Primi passi",
    kurz: "Che cosa fa l'app, com'è organizzata e come arrivi in cinque minuti alla prima trascrizione.",
    bloecke: [
      { art: "p", text: "ResearchTranscript ricava da una registrazione una trascrizione con parlanti e marche temporali. Tutto gira sul tuo Mac. Non c'è nessun account, nessun cloud e nessuna connessione di rete." },
      { art: "h", text: "Le tre sezioni" },
      { art: "liste", punkte: [
        "**Trascrizione IA**: trascini dentro le registrazioni, scegli il numero di parlanti, fai trascrivere.",
        "**Editor umano**: la biblioteca di tutte le trascrizioni. Un clic apre una trascrizione nell'editor, dove ascolti, correggi, dai un nome ai parlanti ed esporti.",
        "**Impostazioni**: posizione, opzioni predefinite, Zotero, privacy e licenze.",
      ] },
      { art: "h", text: "Il primo avvio" },
      { art: "p", text: "Al primo avvio l'app chiede, sotto **Scegli la posizione**, dove devono stare le tue trascrizioni. **Usa la posizione consigliata** crea la cartella nei tuoi Documenti. Con **Scegli un'altra cartella …** prendi una cartella tua, per esempio su un disco cifrato. L'app ricorda l'autorizzazione per questa cartella." },
      { art: "h", text: "In cinque minuti alla trascrizione" },
      { art: "schritte", punkte: [
        "Apri **Trascrizione IA** e trascina un file audio o video sul campo **Trascina qui i file audio**.",
        "Scegli per il file il numero di parlanti.",
        "Fai clic su **Avvia trascrizione**. L'intestazione in alto a sinistra mostra il tempo trascorso e la stima.",
        "Quando l'esecuzione è **Fatto**, apri la trascrizione nell'editor con **Modifica**.",
        "Ascolta con [[Spazio]], correggi il testo, dai un nome ai parlanti nel pannello laterale **Parlanti**.",
        "Scegli sotto **Esporta** il formato che ti serve.",
      ] },
      { art: "bild", datei: "02-ai-transkript", text: "Trascrizione IA: in alto le opzioni, sotto i file in attesa dell'avvio e l'elenco batch delle esecuzioni." },
      { art: "hinweis", text: "Questa finestra di aiuto resta aperta accanto al lavoro. La apri dal menu **Help**, con [[⌘]] [[?]] o con il pulsante **Aiuto** in basso a sinistra nella finestra principale." },
    ],
  },
  {
    id: "transkribieren",
    titel: "Trascrivere",
    kurz: "Mettere in coda i file, scegliere numero di parlanti e opzioni, seguire e annullare le esecuzioni.",
    bloecke: [
      { art: "h", text: "Aggiungere file" },
      { art: "p", text: "Trascina uno o più file sul campo **Trascina qui i file audio** oppure fai clic sul campo e selezionali. Sono supportati MP3, WAV, M4A, OGG e FLAC, come video MP4 e MOV con H.264 o HEVC. Dei video l'app legge l'audio; l'immagine scorre poi muta nell'editor." },
      { art: "h", text: "Opzioni" },
      { art: "tabelle", kopf: ["Opzione", "Significato"], zeilen: [
        ["**Modello Whisper**", "Il modello linguistico. È incluso large-v3-turbo. I modelli propri compaiono qui appena si trovano nella cartella dei modelli (capitolo «Modelli propri»)."],
        ["**Lingua**", "Lingua della registrazione: de, en, fr, it, es oppure auto. Una lingua fissa è più affidabile del riconoscimento automatico."],
        ["**Parlanti** · **Predefinito per i nuovi file**", "Numero di parlanti che un file aggiunto singolarmente riprende: da 1 a 6 oppure **Automatico**. Con 1 il riconoscimento dei parlanti non viene eseguito."],
        ["**Separazione**", "Con quanta severità vengono distinte le voci: **Ampia**, **Normale**, **Rigida**, **Molto rigida**. Rigida tende a separare voci simili in due parlanti, ampia tende a riunirle. L'effetto si nota soprattutto con **Automatico**."],
      ] },
      { art: "h", text: "Pronto per l'avvio: numero di parlanti per file" },
      { art: "p", text: "Ogni file nell'elenco **Pronto per l'avvio** ha il proprio numero di parlanti. Se trascini dentro più file in una volta, devi sceglierlo per ciascun file. Finché per un file compare **Scegli il numero di parlanti**, non parte nessuna esecuzione. Il numero incide molto sul risultato e viene poi riportato nel giornale della trascrizione. **Rimuovi dall'elenco** toglie di nuovo un file. L'elenco si conserva anche dopo un riavvio dell'app." },
      { art: "h", text: "Seguire le esecuzioni" },
      { art: "p", text: "**Avvia trascrizione** manda tutti i file in attesa nell'**Elenco batch**. Un'esecuzione attraversa i passaggi **Conversione audio …**, **Riconoscimento parlanti …**, **Trascrizione …** e **Salvataggio …**. Le registrazioni lunghe vengono trascritte a blocchi; l'indicazione riporta il blocco. In alto a sinistra scorre il tempo, a partire da circa il cinque per cento di avanzamento con una stima della durata totale." },
      { art: "liste", punkte: [
        "**Annulla** termina un'esecuzione. Durante il riconoscimento dei parlanti l'annullamento ha effetto solo quando questo passaggio è concluso.",
        "**Modifica** apre una trascrizione finita nell'editor.",
        "Quante esecuzioni lavorano contemporaneamente lo stabilisci nelle impostazioni sotto **Esecuzioni simultanee**. Più esecuzioni condividono la stessa unità grafica e insieme non sono più veloci che una dopo l'altra.",
      ] },
      { art: "hinweis", text: "Valore indicativo: su un Mac con Apple Silicon un'ora di registrazione richiede pochi minuti. Nel frattempo puoi lavorare nell'editor ad altre trascrizioni." },
    ],
  },
  {
    id: "bibliothek",
    titel: "Biblioteca",
    kurz: "Tutte le trascrizioni in un unico posto: aprire, rinominare, importare, eliminare.",
    bloecke: [
      { art: "p", text: "La sezione **Editor umano** mostra per prima la biblioteca. Ogni riga indica nome, durata, numero di parlanti e di segmenti. Un clic apre la trascrizione nell'editor. Dall'editor torni indietro con **Biblioteca** o con un clic su **Editor umano**." },
      { art: "bild", datei: "03-bibliothek", text: "La biblioteca nella sezione Editor umano." },
      { art: "liste", punkte: [
        "**Rinomina …** cambia il nome della trascrizione. Il nome compare nelle esportazioni e nei nomi dei file.",
        "**Elimina …** sposta la trascrizione nel cestino della biblioteca. Niente viene eliminato definitivamente; la cartella `_papierkorb` si trova nella cartella della biblioteca.",
        "**Mostra nel Finder** apre la cartella della trascrizione.",
        "**Importa trascrizione (VTT/CSV/enrich) …** riprende una trascrizione esistente. Poi l'app chiede il file audio corrispondente; con Annulla importi senza audio.",
      ] },
      { art: "p", text: "Un dossier enrich (.enrich) lo puoi aprire anche con un doppio clic nel Finder o trascinandolo sull'icona dell'app." },
      { art: "hinweis", text: "L'app si avvia con la sezione e la trascrizione con cui l'hai chiusa, alla stessa riga." },
    ],
  },
  {
    id: "editor",
    titel: "Editor: testo e turni",
    kurz: "Correggere il testo, dividere, unire, inserire ed eliminare turni, impostare i tempi di inizio.",
    bloecke: [
      { art: "p", text: "L'editor mostra un segmento per riga: pulsante di riproduzione, tempo di inizio, parlante, testo e a destra le azioni della riga. La riga attiva è evidenziata; durante la riproduzione il suo tempo scorre in centesimi di secondo. Lo stesso tempo compare grande in alto a sinistra e piccolo in basso a destra." },
      { art: "bild", datei: "01-editor", text: "L'editor: trascrizione a sinistra, pannello laterale a destra, in basso forma d'onda e barra di controllo." },
      { art: "h", text: "Modificare il testo" },
      { art: "p", text: "Fai clic nel testo e scrivi. L'app salva da sola; in alto compare **Salvataggio …** e poi **Salvato** con l'ora. Prima di ogni salvataggio archivia lo stato precedente nella cartella `history` della trascrizione (gli ultimi 30)." },
      { art: "h", text: "Dividere, inserire, unire, eliminare turni" },
      { art: "tasten", zeilen: [
        ["[[Invio]] in mezzo al testo", "Divide il segmento al cursore. La seconda parte riceve il tempo stimato del punto di taglio."],
        ["[[Invio]] a fine testo", "Crea subito dopo un nuovo turno vuoto."],
        ["[[⌥]] [[Invio]]", "Intervento: crea un nuovo turno con il tempo della posizione di riproduzione attuale e vi porta il cursore. Funziona anche mentre stai scrivendo."],
        ["[[⌫]] a inizio testo", "Unisce il segmento al precedente."],
        ["[[⌫]] nel campo vuoto", "Elimina il segmento."],
      ] },
      { art: "p", text: "Le stesse azioni le trovi come icone a destra nella riga: **Dividi al cursore**, **Unisci al precedente**, **Elimina segmento** e **Memo per questa riga**." },
      { art: "bild", datei: "11-zeile", text: "Una riga: pulsante di riproduzione, tempo di inizio, parlante, testo, azioni. Il punto rosso indica un memo." },
      { art: "h", text: "Modificare il tempo di inizio" },
      { art: "p", text: "Fai clic sul tempo di una riga. Inserisci il nuovo tempo di inizio come hh:mm:ss.hh, per esempio 00:19:10.45, e conferma con [[Invio]]. [[Esc]] annulla. Vanno bene anche forme più brevi come 19:10 o 75.5. La riga si colloca secondo il suo nuovo tempo." },
      { art: "h", text: "Cambiare il parlante di una riga" },
      { art: "p", text: "Un clic sull'etichetta del parlante apre il menu. I parlanti scelti per ultimi stanno in alto. **Nuovo parlante** crea una nuova persona, **senza parlante** rimuove l'assegnazione." },
      { art: "h", text: "Dimensione del carattere" },
      { art: "p", text: "La dimensione del testo dei turni la regoli nelle impostazioni sotto **Dimensione testo dei turni**." },
    ],
  },
  {
    id: "wiedergabe",
    titel: "Riproduzione e forma d'onda",
    kurz: "Riprodurre, saltare, velocità, ciclo, seguire, zoom sulla forma d'onda, video.",
    bloecke: [
      { art: "bild", datei: "09-wiedergabe", text: "Forma d'onda con i marcatori dei memo, sotto la barra di controllo: trasporto, velocità, modalità di riproduzione, a destra il tempo." },
      { art: "h", text: "Barra di controllo" },
      { art: "tabelle", kopf: ["Elemento", "Effetto"], zeilen: [
        ["Trasporto", "5 s indietro, riproduzione o pausa, 5 s avanti."],
        ["Velocità − valore +", "**Più lento** e **Più veloce** nei livelli da 0,75× a 2×. Un clic sul valore ripristina 1×."],
        ["**Ciclo**", "Ripete il segmento attivo finché non disattivi il ciclo."],
        ["**Segui**", "L'elenco segue la riproduzione: la riga attiva resta nella zona centrale della finestra."],
      ] },
      { art: "p", text: "Il pulsante di riproduzione all'inizio di ogni riga riproduce **Da qui** e al secondo clic si ferma di nuovo." },
      { art: "h", text: "Forma d'onda" },
      { art: "p", text: "La forma d'onda mostra la registrazione nei colori dei parlanti. La linea verticale è la posizione di riproduzione." },
      { art: "liste", punkte: [
        "Un clic o un trascinamento imposta la posizione di riproduzione.",
        "[[⌘]] + rotella di scorrimento o il gesto di allargare due dita ingrandisce attorno al puntatore.",
        "Lo scorrimento orizzontale o [[⇧]] + rotella di scorrimento sposta la porzione visibile.",
        "Un doppio clic mostra di nuovo l'intera registrazione.",
        "Durante la riproduzione la porzione visibile avanza appena la linea raggiunge il bordo.",
        "I punti rossi nella traccia superiore sono memo. Il puntatore sopra ne mostra il testo, un clic apre il memo.",
      ] },
      { art: "h", text: "Video" },
      { art: "p", text: "Con una sorgente video l'immagine scorre muta accanto alla trascrizione; l'audio viene dalla traccia audio della trascrizione. A 2× l'immagine resta ferma finché non rallenti." },
      { art: "p", text: "Se nella barra di controllo compare **Nessun audio collegato**, la trascrizione è stata importata senza file audio." },
    ],
  },
  {
    id: "sprecher",
    titel: "Parlanti",
    kurz: "Dare un nome ai parlanti, colorarli, ascoltarli, unirli e assegnare le righe vuote.",
    bloecke: [
      { art: "p", text: "Il pannello laterale **Parlanti** elenca tutte le persone della trascrizione con il numero dei loro segmenti. Dopo la trascrizione prendono dapprima il nome dal loro numero." },
      { art: "bild", datei: "05-sprecherfarbe", text: "Pannello laterale Parlanti con la scelta del colore aperta." },
      { art: "liste", punkte: [
        "**Rinomina**: scrivi il nome nel campo. Cambia subito in tutte le righe e le esportazioni.",
        "**Scegli il colore**: il cerchio colorato apre la tavolozza. Il colore vale per l'etichetta, la forma d'onda e l'esportazione REFI-QDA.",
        "**Campione**: riproduce un breve estratto di questa voce, così la riconosci.",
        "**Unisci in …**: attribuisce tutti i segmenti di questa persona a un'altra. Serve quando il riconoscimento ha diviso una voce in due.",
        "**Assegna a tutti senza parlante**: dà questa persona a tutte le righe senza parlante.",
      ] },
      { art: "hinweis", text: "I parlanti sono voci a sé, non testo davanti alla riga. Rinominare e unire non cambiano quindi mai il testo pronunciato." },
    ],
  },
  {
    id: "suchen",
    titel: "Cerca e sostituisci",
    kurz: "Trovare parole, verificarle una per una e sostituirle, per esempio per gli pseudonimi.",
    bloecke: [
      { art: "p", text: "Il pannello laterale **Cerca** cerca nel testo della trascrizione aperta. Inserisci sotto **Cerca** il termine e, se vuoi sostituire, sotto **Sostituisci con** il nuovo testo." },
      { art: "bild", datei: "04-suchen-ersetzen", text: "Cerca e sostituisci: i risultati sono evidenziati nella trascrizione." },
      { art: "liste", punkte: [
        "**Risultato precedente** e **Risultato successivo** saltano da un'occorrenza all'altra; l'indicazione riporta la posizione, per esempio 3 di 12.",
        "**Sostituisci** sostituisce il risultato attuale, **Salta** lo lascia com'è e passa oltre.",
        "**Sostituisci tutto** sostituisce ogni risultato in una volta.",
        "**Ignora la sillabazione** trova anche forme scritte divise come «coope- rativa».",
        "**Distingui maiuscole** distingue «Casa» e «casa».",
      ] },
      { art: "hinweis", text: "La ricerca è letterale: nessuna traduzione, nessuna forma base. Per gli pseudonimi cerchi quindi ogni grafia di un nome separatamente." },
    ],
  },
  {
    id: "memos",
    titel: "Memo",
    kurz: "Note tue per ogni riga, separate dal testo pronunciato, con esportazione in CSV e REFI-QDA.",
    bloecke: [
      { art: "p", text: "Un memo è la tua nota su una riga: un'osservazione, una domanda da chiarire, una prima idea per l'analisi. È tuo e non fa parte del testo pronunciato." },
      { art: "bild", datei: "08-memo", text: "Il memo di una riga." },
      { art: "schritte", punkte: [
        "Fai clic a destra nella riga su **Memo per questa riga**.",
        "Scrivi la nota e conferma con **Salva** o [[⌘]] [[Invio]].",
        "**Elimina memo** lo rimuove di nuovo.",
      ] },
      { art: "p", text: "Una riga con memo porta un punto rosso sull'icona. Nella forma d'onda compare al suo posto un marcatore rosso." },
      { art: "tabelle", kopf: ["Esportazione", "Che cosa succede al memo"], zeilen: [
        ["CSV", "Colonna dedicata «Memo». Più memo di uno stesso turno sono separati da « | »."],
        ["REFI-QDA", "Memo sul passaggio codificato; ATLAS.ti e MAXQDA lo mostrano lì."],
        ["VTT, TXT", "Non incluso."],
        ["Dossier enrich", "Non ancora incluso."],
      ] },
    ],
  },
  {
    id: "metadaten",
    titel: "Metadati e Zotero",
    kurz: "Riprendere titolo, data, intervistatori e citekey dalla biblioteca Zotero locale.",
    bloecke: [
      { art: "p", text: "Nel pannello laterale **Metadati** colleghi una trascrizione a una voce della tua biblioteca Zotero. Titolo, data, intervistatore o intervistatrice e citekey compaiono poi nel dossier enrich. Zotero viene solo letto e mai modificato; può restare aperto." },
      { art: "h", text: "Abilitare una volta" },
      { art: "schritte", punkte: [
        "Apri **Impostazioni** e la scheda **Zotero**.",
        "Attiva **Consenti la lettura del database Zotero locale**.",
        "Scegli con **Modifica …** la cartella di Zotero, di solito `Zotero` nella tua cartella utente. L'app ha bisogno di questa autorizzazione perché gira in un ambiente protetto.",
        "Se sotto compare **Trovato**, il database è leggibile.",
      ] },
      { art: "h", text: "Collegare" },
      { art: "schritte", punkte: [
        "Apri nell'editor il pannello laterale **Metadati**.",
        "Cerca per titolo, anno, nome o citekey.",
        "Scegli la voce e fai clic su **Collega**.",
        "Stabilisci i ruoli sotto **Quali persone entrano nella trascrizione?**.",
      ] },
      { art: "p", text: "**Ricarica** riprende da Zotero i dati modificati, **Mostra in Zotero** apre lì la voce, **Scollega** rimuove il collegamento." },
      { art: "hinweis", text: "La parte intervistata (interviewee, guest, castMember) non è preselezionata. Una trascrizione pseudonimizzata non deve ricevere il suo nome tramite Zotero." },
    ],
  },
  {
    id: "export",
    titel: "Esportazione",
    kurz: "Quale formato per che cosa: VTT, CSV, TXT, REFI-QDA e dossier enrich.",
    bloecke: [
      { art: "p", text: "In alto nell'editor **Esporta** apre l'elenco dei formati. Dopo la scelta l'app chiede dove salvare. Le esportazioni sono derivate: la trascrizione nella biblioteca resta la fonte, puoi esportare di nuovo in qualsiasi momento." },
      { art: "bild", datei: "06-export", text: "I formati di esportazione nell'editor." },
      { art: "tabelle", kopf: ["Formato", "Contenuto", "A che cosa serve"], zeilen: [
        ["VTT", "Sottotitoli con tempi in millisecondi, parlante come voice tag. I passaggi molto brevi vengono uniti in sottotitoli leggibili, quelli lunghi divisi.", "Lettori video, programmi di montaggio, reimportazione."],
        ["CSV", "Una riga per turno: Time-in, Time-out, Speaker, Text, Memo. Tempi come hh:mm:ss.hh.", "Tabelle, analisi proprie, reimportazione."],
        ["TXT", "Testo continuo, un paragrafo per turno con il nome del parlante. Senza tempi.", "Leggere, citare, condividere."],
        ["Markdown (.md), Word (.docx)", "Versione di lettura con intestazione (durata, parlanti, con collegamento a Zotero data, persone, citekey), per ogni turno parlante e tempo di inizio, memo come blocco di citazione.", "Leggere, commentare, depositare in un archivio."],
        ["**REFI-QDA per ATLAS.ti (.qdpx.zip)**", "File di progetto con testo, audio, marche temporali per ogni enunciato, parlanti come codici e memo.", "ATLAS.ti, MAXQDA, NVivo."],
        ["**REFI-QDA con video (.qdpx.zip)**", "Come sopra, con il file video al posto della traccia audio. Solo con sorgenti video.", "Analisi video in software QDA."],
        ["**Dossier enrich (.enrich)**", "Trascrizione, audio in MP3, metadati Zotero e un giornale di chi ha modificato che cosa e quando.", "Proseguire il lavoro in enrich, archivio."],
      ] },
      { art: "p", text: "Sotto la linea di separazione c'è **Pacchetto di documentazione (.zip) …**. Documenta come è nata questa trascrizione; maggiori dettagli nel capitolo «Documentazione per la ricerca»." },
      { art: "hinweis", text: "L'esportazione REFI-QDA è uno zip. Decomprimilo: dentro ci sono il file di progetto `.qdpx` e una cartella con il file multimediale. Importa il file `.qdpx` nel tuo software QDA e lascia accanto la cartella del file multimediale." },
    ],
  },
  {
    id: "dokumentation",
    titel: "Documentazione per la ricerca",
    kurz: "Il pacchetto di documentazione di una trascrizione: protocollo, modulo metodologico, scheda per il deposito, modulo per il registro dei trattamenti e file di citazione — generati dai valori reali.",
    bloecke: [
      { art: "p", text: "L'app sa quale modello è stato usato, quando è avvenuta la trascrizione e quanto hai modificato la trascrizione grezza. Da questi dati genera i documenti che ti servono per la sezione metodi, la protezione dei dati e l'archivio dei dati. Le affermazioni valgono per la singola trascrizione. Ciò che sai solo tu resta un campo aperto `[ … ]`: chi ha corretto, secondo quali regole, con quale consenso." },
      { art: "h", text: "Come procedi" },
      { art: "schritte", punkte: [
        "Apri la trascrizione nell'editor e scegli sotto **Esporta** la voce **Pacchetto di documentazione (.zip) …**.",
        "Scegli dove salvare. Lo zip contiene ogni documento in .md e in .docx, ma nessuna trascrizione e nessuna registrazione.",
        "Compila i campi aperti `[ … ]` e verifica ogni proposta proveniente da Zotero.",
      ] },
      { art: "h", text: "Che cosa contiene il pacchetto" },
      { art: "tabelle", kopf: ["Documento", "A che cosa serve"], zeilen: [
        ["Protocollo di trascrizione", "Provenienza: modello, versione, data, modifica a mano, misura dell'intervento, file con somme di controllo. Fa parte della documentazione dei dati e può accompagnare il pacchetto di dati. Non riporta i nomi di chi parla."],
        ["Modulo metodologico", "Dati essenziali, procedimento e misura dell'intervento di questa trascrizione, più un paragrafo per la sezione metodi con riferimenti."],
        ["Scheda per il deposito", "Campi secondo Zenodo e DataCite, integrati con ciò che richiedono archivi specializzati come SWISSUbase o Qualiservice. Precompilata da Zotero e dalla trascrizione, con elenco dei file, somme di controllo e una lista di controllo etica."],
        ["Modulo per il registro dei trattamenti", "Per il registro delle attività di trattamento, la valutazione d'impatto sulla protezione dei dati e la domanda alla commissione etica: che cosa l'app fa e non fa, dove stanno i dati; campi aperti per il titolare del trattamento."],
        ["File di citazione `researchtranscript.bib`", "ResearchTranscript come voce «Software», più Whisper, pyannote e le altre fonti. In Zotero da File › Importa."],
      ] },
      { art: "h", text: "La misura dell'intervento" },
      { art: "p", text: "Alla creazione di una trascrizione l'app ne salva lo stato iniziale automatico. Rispetto a questo misura poi quanto è stata modificata a mano:" },
      { art: "liste", punkte: [
        "Tasso di correzione a livello di parola: parole sostituite, eliminate e inserite, divise per le parole della versione finale. Calcolato come il tasso di errore sulle parole (WER), con la versione finale come riferimento. Una volta normalizzato (in minuscolo, senza punteggiatura) e una volta ortografico (maiuscole, minuscole e punteggiatura contano).",
        "Tempo di parola riassegnato: quota del tempo di parola di cui hai cambiato il parlante. In più una lettura in cui l'unione di due voci non conta.",
      ] },
      { art: "hinweis", text: "È una misura dell'intervento, non una misura della precisione. Il tasso comprende anche pseudonimizzazione e levigatura del testo, e non coglie gli errori che nessuno ha notato. Per le trascrizioni di versioni precedenti lo stato iniziale può mancare; in tal caso il protocollo lo dice." },
      { art: "h", text: "Pubblicare dati di interviste" },
      { art: "liste", punkte: [
        "La registrazione audio contiene la voce ed è un dato personale. Non va in un repository aperto.",
        "Pseudonimizzato non significa anonimo. Per i dati sensibili un archivio specializzato con controllo degli accessi è più adatto di Zenodo.",
        "I metadati sono sempre pubblici: nessun nome in titolo, descrizione, parole chiave e nomi dei file.",
        "Le persone intervistate non compaiono mai come autori. Da Zotero l'app propone solo persone che non appartengono alla parte intervistata.",
      ] },
    ],
  },
  {
    id: "einstellungen",
    titel: "Impostazioni",
    kurz: "Tutte le schede delle impostazioni e l'effetto delle loro opzioni.",
    bloecke: [
      { art: "bild", datei: "07-einstellungen", text: "Le impostazioni." },
      { art: "h", text: "Posizione" },
      { art: "p", text: "La cartella della biblioteca. Per ogni trascrizione nasce una sottocartella con trascrizione, audio e cronologia. **Modifica …** sceglie un'altra cartella; l'app non sposta le trascrizioni esistenti. **Mostra nel Finder** apre la cartella." },
      { art: "h", text: "Opzioni predefinite" },
      { art: "tabelle", kopf: ["Opzione", "Significato"], zeilen: [
        ["**Modello Whisper**", "Valore predefinito per le nuove esecuzioni."],
        ["**Lingua**", "Valore predefinito per la lingua delle registrazioni."],
        ["**Esecuzioni simultanee**", "Da 1 a 4. Consigliato è **1 — uno dopo l'altro**."],
        ["**Lingua dell'interfaccia**", "Deutsch, English, Français, Italiano. Vale subito, anche per questa finestra di aiuto."],
        ["**Dimensione testo dei turni**", "Dimensione del carattere del testo della trascrizione nell'editor."],
      ] },
      { art: "h", text: "Identità nel dossier" },
      { art: "p", text: "**E-mail come ID utente (facoltativo)** scrive il tuo indirizzo nel giornale di ogni dossier enrich che esporti. Lascia il computer solo con questo file. L'**ID di questa installazione** è casuale e non ha alcun legame con il dispositivo o la persona; **Rigenera** ne assegna uno nuovo." },
      { art: "h", text: "Zotero" },
      { art: "p", text: "Abilitazione e cartella del database Zotero, vedi il capitolo «Metadati e Zotero»." },
      { art: "h", text: "Privacy" },
      { art: "p", text: "Riassume che tutto resta in locale. **Informativa sulla privacy** apre il testo completo. **Apri il registro** mostra il registro locale dell'app; aiuta nella ricerca degli errori e non viene mai inviato." },
      { art: "h", text: "Licenze, ResearchTranscript, Formati, BIAS.City" },
      { art: "p", text: "Queste schede indicano i componenti inclusi e le loro licenze (**Tutte le licenze (elenco)**), il codice sorgente, le specifiche dei formati di esportazione e l'istituto dietro l'app." },
      { art: "hinweis", text: "Chiaro e scuro seguono l'impostazione di macOS in Impostazioni di Sistema › Aspetto." },
    ],
  },
  {
    id: "modelle",
    titel: "Modelli propri",
    kurz: "Usare altri modelli whisper.cpp, per esempio per lo svizzero tedesco.",
    bloecke: [
      { art: "p", text: "L'app include il modello large-v3-turbo. Puoi usare altri modelli whisper.cpp in formato ggml, per esempio un fine-tuning per lo svizzero tedesco o una variante più piccola e quantizzata." },
      { art: "schritte", punkte: [
        "Apri **Impostazioni**, scheda **Opzioni predefinite**, sezione **Modelli propri**.",
        "Fai clic su **Mostra nel Finder** e metti il file in questa cartella. Il nome deve seguire lo schema `ggml-….bin`.",
        "Fai clic su **Rileggi**. Il modello compare nella selezione **Modello Whisper**, contrassegnato come **proprio**.",
      ] },
      { art: "p", text: "Un modello proprio con lo stesso nome sostituisce quello incluso. L'app non scarica mai modelli da sola." },
      { art: "h", text: "Se un modello non compare" },
      { art: "tabelle", kopf: ["Messaggio", "Che cosa fare"], zeilen: [
        ["**copia in corso**", "Aspetta che il Finder abbia finito, poi **Rileggi**."],
        ["**non è un modello whisper.cpp (ggml)**", "Il file ha un altro formato, per esempio PyTorch o Core ML. Ti serve la versione ggml."],
        ["**incompleto (troppo piccolo per un modello)**", "Il download si è interrotto. Scarica di nuovo il file."],
        ["**solo su iCloud**", "Scaricalo nel Finder tramite l'icona della nuvola."],
        ["**ignorato (il nome deve essere ggml-….bin)**", "Rinomina il file."],
      ] },
      { art: "hinweis", text: "Con che cosa è stato trascritto è riportato nel giornale di ogni trascrizione. I modelli propri non fanno parte dell'elenco nella scheda sulla privacy del sito web; indicali tu stesso nella tua documentazione." },
    ],
  },
  {
    id: "tasten",
    titel: "Scorciatoie da tastiera",
    kurz: "Tutte le scorciatoie dell'editor, anche per i pedali.",
    bloecke: [
      { art: "p", text: "Nell'editor ci sono due livelli: fuori da un campo di testo, tasti semplici comandano la riproduzione. Mentre scrivi i tasti appartengono al testo; gli stessi comandi si trovano allora su [[⌥]]. [[Esc]] esce dal campo di testo." },
      { art: "h", text: "Riproduzione" },
      { art: "tabelle", kopf: ["Comando", "Fuori dal testo", "Mentre scrivi"], zeilen: [
        ["Riproduzione / pausa", "[[Spazio]] o [[K]]", "[[⇧]] [[Spazio]], [[⌥]] [[Spazio]] o [[⌥]] [[K]]"],
        ["5 s indietro", "[[J]] o [[←]]", "[[⌥]] [[J]]"],
        ["5 s avanti", "[[L]] o [[→]]", "[[⌥]] [[L]]"],
        ["Turno precedente / successivo", "[[↑]] / [[↓]]", "[[⌥]] [[↑]] / [[⌥]] [[↓]] – il cursore si sposta insieme"],
        ["Turno precedente / successivo (pedale)", "[[fn]] [[↑]] / [[fn]] [[↓]] (Pagina su / Pagina giù)", "uguale"],
        ["Ciclo attivo / disattivo", "[[Ctrl]] [[L]]", "[[Ctrl]] [[L]]"],
        ["Velocità successiva", "[[Ctrl]] [[X]]", "[[Ctrl]] [[X]]"],
      ] },
      { art: "h", text: "Testo e turni" },
      { art: "tasten", zeilen: [
        ["[[Invio]]", "Divide il segmento al cursore; a fine testo: nuovo turno."],
        ["[[⌥]] [[Invio]]", "Inserisce un intervento alla posizione di riproduzione."],
        ["[[⌫]] a inizio testo", "Unisce al segmento precedente."],
        ["[[⌫]] nel campo vuoto", "Elimina il segmento."],
        ["[[Esc]]", "Esce dal campo di testo; poi valgono di nuovo i tasti semplici."],
        ["[[⌘]] [[Z]] / [[⇧]] [[⌘]] [[Z]]", "Annulla e ripristina nel campo di testo."],
      ] },
      { art: "h", text: "Altre" },
      { art: "tasten", zeilen: [
        ["[[Invio]] / [[Esc]] nel campo del tempo", "Conferma / scarta il tempo di inizio."],
        ["[[⌘]] [[Invio]] nel memo", "Salva il memo."],
        ["[[⌘]] + rotella di scorrimento sulla forma d'onda", "Zoom."],
        ["[[⇧]] + rotella di scorrimento sulla forma d'onda", "Sposta la porzione visibile."],
        ["Doppio clic sulla forma d'onda", "Mostra l'intera registrazione."],
        ["[[⌘]] [[?]]", "Apre questo aiuto."],
      ] },
      { art: "h", text: "Pedale" },
      { art: "p", text: "Un pedale che invia tasti lo configuri nel suo software con Pagina su e Pagina giù per il cambio di turno e con [[⇧]] [[Spazio]] per riproduzione e pausa. Queste scorciatoie funzionano anche mentre scrivi." },
    ],
  },
  {
    id: "daten",
    titel: "Dati, privacy e risoluzione dei problemi",
    kurz: "Dove stanno i tuoi dati, che cosa l'app non fa mai e che cosa aiuta in caso di problemi.",
    bloecke: [
      { art: "h", text: "Dove stanno i dati" },
      { art: "p", text: "Tutto sta nella cartella della biblioteca, una sottocartella per trascrizione:" },
      { art: "tabelle", kopf: ["File", "Contenuto"], zeilen: [
        ["`transkript.json`", "La trascrizione: segmenti, parlanti, memo, giornale. L'unica fonte; le esportazioni ne sono derivate."],
        ["`audio.…`", "Copia della registrazione, per i video in più il file video."],
        ["`ausgang.json`", "Lo stato iniziale automatico inalterato. Rispetto a questo l'app calcola la misura dell'intervento."],
        ["`history/`", "Gli ultimi 30 stati prima di ogni salvataggio."],
        ["`wellenform.json`", "Cache della forma d'onda; viene ricreata quando serve."],
        ["`_papierkorb/`", "Trascrizioni eliminate, nella cartella della biblioteca. Puoi svuotarlo nel Finder."],
      ] },
      { art: "hinweis", text: "Per i backup salvi la cartella della biblioteca. Per passare a un altro Mac la copi e la scegli lì come posizione." },
      { art: "hinweis", text: "Se pseudonimizzi nell'editor, cambia la versione finale. `ausgang.json`, `history/` e la registrazione continuano a contenere il testo originale con i nomi reali. Non trasmettere questi file, ed eliminali nel Finder se il tuo progetto lo richiede. Dopo non è più possibile calcolare la misura dell'intervento." },
      { art: "h", text: "Che cosa l'app non fa mai" },
      { art: "liste", punkte: [
        "Non trasmette niente: nessuna registrazione, nessun testo, nessun dato di utilizzo.",
        "Non scarica modelli né parti di programma.",
        "Legge solo le cartelle che hai scelto e i file che trascini dentro.",
        "Non modifica Zotero.",
      ] },
      { art: "h", text: "Se qualcosa non funziona" },
      { art: "tabelle", kopf: ["Che cosa osservi", "Che cosa aiuta"], zeilen: [
        ["Banner «L'elaborazione non risponde da alcuni secondi …»", "**Riavvia l'app**. Il lavoro in corso è salvato."],
        ["L'esecuzione termina con **Non riuscito**", "Il messaggio indica il motivo, per esempio un formato video non supportato. Converti il file in MP4 (H.264) o in un formato audio."],
        ["Numero di parlanti sbagliato", "Trascrivi di nuovo con un numero fisso di parlanti invece di **Automatico**, oppure unisci i parlanti nell'editor."],
        ["Molti errori con dialetto o linguaggio specialistico", "Scegli una **Lingua** fissa; per lo svizzero tedesco usa un modello proprio."],
        ["Zotero non viene trovato", "Nelle impostazioni scegli di nuovo la cartella di Zotero con **Modifica …**."],
        ["Qualcos'altro", "**Impostazioni › Privacy › Apri il registro** e guarda le ultime righe o allegale alla segnalazione."],
      ] },
      { art: "p", text: "Domande e segnalazioni di errori: bias.city/researchtranscript oppure le issue nel repository GitHub bias-city/ResearchTranscript." },
    ],
  },
];

export default kapitel;
