"""Texts of the documentation package — English. Keys, placeholders, lines and columns identical to de.py."""

T = {
    # ---- general ----
    "feld": "Field", "wert": "Value", "datei": "File", "groesse": "Size", "hinweis": "Note",
    "eintrag": "Entry", "dezimal": ".", "nicht_aufgezeichnet": "not recorded",
    "fuss": "Generated by ResearchTranscript {v} on {datum} for “{name}”. Open fields `[ … ]` are completed by the researchers.",
    "von": "{n} of {gesamt} ({anteil})",

    # ---- folders and file names (ASCII, lowercase, hyphens) ----
    "paket.ordner": "documentation", "ordner.methoden": "1-methods", "ordner.datenschutz": "2-data-protection",
    "ordner.ablage": "3-data-deposit", "ordner.zitieren": "cite",
    "datei.liesmich": "README", "datei.protokoll": "transcription-record",
    "datei.absatz": "methods-paragraph", "datei.tatsachen": "app-facts",
    "datei.stelle": "controller-details", "datei.datensatz": "data-sheet-dataset",
    "datei.interview": "data-sheet-interview", "datei.ethik": "ethics-checklist",
    "datei.repos": "repositories-and-requirements",

    # ---- README ----
    "l.titel": "Documentation package",
    "l.text": "Companion documents for one transcript, generated from the values the app knows. The package contains neither the transcript nor the recording.",
    "l.wofuer": "Purpose",
    "l.zeilen": "{methoden}/{protokoll} :: How the transcript came about and how heavily it was edited by hand. Belongs to the data documentation.\n"
                "{methoden}/{absatz} :: Paragraph for the methods section, short and detailed.\n"
                "{datenschutz}/{tatsachen} :: What the app does and does not do. For records of processing activities, data protection impact assessment, ethics application.\n"
                "{datenschutz}/{stelle} :: What only the controller knows, as a form.\n"
                "{ablage}/{datensatz} :: Fields for Zenodo and DataCite, once per dataset.\n"
                "{ablage}/{interview} :: Details of this one interview.\n"
                "{ablage}/{ethik} :: Check items before publication.\n"
                "{ablage}/{repos} :: Which repository, which formats, which requirements.\n"
                "{zitieren}/researchtranscript.bib :: Software and models as items for Zotero (File › Import).",
    "l.vorher": "Before sharing",
    "l.vorher.punkte": "The name of the transcript, the source file and file names in this package may name persons. Check before sharing.\n"
                       "The audio recording contains the voice and is personal data.\n"
                       "Pseudonymised is not anonymised. Data protection law continues to apply.\n"
                       "`ausgang.json`, `history/` and the recording contain the wording before any pseudonymisation.\n"
                       "The documents are not legal advice.",

    # ---- 1a Transcription record ----
    "p.titel": "Transcription record",
    "p.einleitung": "The record states how this transcript came about and how heavily it was edited by hand. The details are taken from the transcript and its journal.",
    "p.transkript": "Transcript", "p.maschine": "Machine transcription", "p.hand": "Editing by hand",
    "p.eingriff": "Intervention compared with the machine transcript", "p.dateien": "Files",
    "p.software": "Software and models",
    "f.name": "Name in the library", "f.quelldatei": "Source file", "f.dauer": "Duration of the transcript",
    "f.sprache": "Language (setting)", "f.segmente": "Segments", "f.sprecher": "Speakers in the final version",
    "f.memos": "Memos", "f.zotero": "Zotero", "zotero.ja": "linked", "zotero.nein": "not linked",
    "f.datum": "Date of the run", "f.app": "App", "f.erkennung": "Speech recognition",
    "f.vad": "Voice activity detection", "f.trennung": "Speaker diarisation", "f.ort": "Place of processing",
    "app.vorgaenger": "{name} {version} (former name of ResearchTranscript; version numbering restarted at 0.4.0)",
    "erkennung.wert": "whisper.cpp {whisper}, model `{modell}` ({herkunft})",
    "erkennung.alt": "whisper.cpp, model `{modell}`; program version not recorded at the time of the run",
    "modell.mitgeliefert": "shipped with the app", "modell.eigen": "the researchers' own model",
    "modell.unbekannt": "origin not recorded",
    "vad.an": "Silero VAD {silero} in whisper.cpp", "vad.aus": "not used",
    "vad.diar": "not used; speaker diarisation cuts the blocks",
    "diar.aus": "switched off",
    "diar.an": "SpeakerKit (Argmax); models pyannote segmentation-3.0, WeSpeaker ResNet34 and pyannote community-1, converted to Core ML by Argmax. Number of speakers: {zahl}",
    "diar.auto": "automatic", "diar.schwelle": "clustering threshold {wert}",
    "ort.neu": "locally on the Mac; speech recognition in a helper program from the app bundle",
    "ort.alt": "locally on the Mac",
    "p.importiert": "This transcript was imported from `{datei}`, not transcribed in the app. The baseline is the file as it arrived.",
    "f.sitzungen": "Editing sessions", "f.zeitraum": "Period", "f.wer": "Edited by (sessions)",
    "f.rolle": "Role of the editors", "f.abgehoert": "Checked against the recording by listening",
    "f.regeln": "Transcription rules", "f.pseudonym": "Pseudonymisation",
    "sitzungen.text": "{n} (runs of saves from the same installation with pauses of less than ten minutes)",
    "wer.eintrag": "{wer} ({n})", "wer.install": "installation {kennung}",
    "offen.rolle": "[ … ]", "offen.abgehoert": "[ in full / in part / no ]",
    "offen.regeln": "[ … ] (e.g. Dresing & Pehl, simple or extended)",
    "offen.pseudonym": "[ … ] (what was replaced, by which rule)",
    "e.journal": "According to the journal, per segment",
    "e.journal.text": "For each session the journal notes which segments were changed. Distinct segments are counted; if a segment has several changes within one session, the last one counts. The shares are therefore minimum values.",
    "e.j.text": "Wording changed", "e.j.sprecher": "Speaker reassigned", "e.j.zeit": "Timing changed",
    "e.j.summe": "Segments with at least one change",
    "e.j.weitere": "In addition: {neu} entries newly created, {weg} removed, {name} speakers renamed.",
    "e.wort": "Against the machine baseline, per word",
    "e.wort.fehlt": "A per-word rate cannot be computed for this transcript. It was created with a version that did not yet keep the raw machine state.",
    "e.wort.verlauf": "The baseline was taken from the oldest unedited state in the history.",
    "mass.kopf": "Measure", "mass.basis": "Basis",
    "mass.norm": "Correction rate, normalised", "mass.orth": "Correction rate, orthographic",
    "mass.sdi": "{s} substituted, {d} deleted, {i} inserted; {n} words in the final version",
    "mass.sprechzeit": "Reassigned speech time",
    "mass.sprechzeit.basis": "speech time covered by both states {zeit}; {a} speakers in the baseline, {b} in the final version",
    "mass.mehrheit": "of which, not counting merged speakers",
    "mass.mehrheit.text": "merging two voices does not count here",
    "mass.ohne_maschine": "the machine assigned no speakers",
    "mass.definition": "Correction rate = (substituted + deleted + inserted words) ÷ words of the final version. Counting follows the word error rate, with the final version as the reference, aligned per segment. *Normalised*: lower-cased, without punctuation and special characters. *Orthographic*: as written. Reassigned speech time = share of the speech time covered by both states that has a different speaker, under the best possible one-to-one mapping.",
    "mass.vorbehalt": "A measure of intervention, not a measure of accuracy. It counts every change made by hand, including pseudonymisation and smoothing. It does not capture errors that went unnoticed.",
    "dateien.text": "Files in the transcript's folder, with SHA-256.",
    "dateien.ausgang": "`ausgang.json` is the unaltered baseline. It contains the wording before any pseudonymisation.",
    "software.punkte": "whisper.cpp (MIT): <https://github.com/ggml-org/whisper.cpp>\n"
                       "Whisper large-v3-turbo (OpenAI, MIT): <https://huggingface.co/openai/whisper-large-v3-turbo>\n"
                       "SpeakerKit, Argmax OSS (MIT): <https://github.com/argmaxinc/argmax-oss-swift>\n"
                       "pyannote speaker-diarization-community-1 (CC BY 4.0): <https://huggingface.co/pyannote/speaker-diarization-community-1>\n"
                       "Silero VAD (MIT): <https://github.com/snakers4/silero-vad>\n"
                       "ResearchTranscript (AGPL-3.0-or-later): <https://github.com/bias-city/ResearchTranscript>",

    # ---- 1b Methods paragraph ----
    "a.titel": "Paragraph for the methods section",
    "a.einleitung": "To be adopted and adapted. Square brackets are to be replaced. The paragraph applies to this one transcript.",
    "a.kurz": "Short version", "a.lang": "Detailed, for an appendix or data management plan",
    "a.app.neu": "ResearchTranscript {version}", "a.app.alt": "{name} {version} (now ResearchTranscript)",
    "a.s1": "The recording (duration {dauer}) was transcribed locally with {app} [ on a computer of the research group ]; the app transmits no data in the process.",
    "a.s2": "Speech recognition used whisper.cpp with the model {modell}.",
    "a.s3": "Speakers were separated by SpeakerKit with pyannote models.",
    "a.s4": "The raw transcript was checked against the recording [ by whom ] [ in full / on a sample basis ] and corrected according to [ transcription rules ] [ and pseudonymised in the text ].",
    "a.s5.wort": "The word-level correction rate was {norm} (normalised, final version as the reference){sprechzeit}.",
    "a.s5.sprechzeit": "; {wert} of the speech time was reassigned by hand",
    "a.s5.journal": "According to the journal, the wording was changed in at least {text} of the segments and the speaker was reassigned in {sprecher}.",
    "a.s6": "The values measure the intervention, not the accuracy.",
    "a.k1": "The recording was transcribed locally with {app} (whisper.cpp, model {modell}) and then checked against the recording and corrected [ by whom ].",
    "a.offen": "Still to be added",
    "a.offen.punkte": "Who made the corrections and whether the recording was listened to in full.\n"
                      "Which transcription rules were followed.\n"
                      "What was pseudonymised and by which rule.",
    "a.zitieren": "Citing",
    "a.zitieren.text": "Pohl, B. ({jahr}). ResearchTranscript (Version {v}) [Software]. B/IAS – Basel Institut für angewandte Stadtforschung. <https://bias.city/researchtranscript/> The file `researchtranscript.bib` in the folder `{zitieren}` contains this item and the models for Zotero.",

    # ---- 2a App facts ----
    "t.titel": "ResearchTranscript: facts for data protection and ethics application",
    "t.einleitung": "Facts about the app, to be adopted in records of processing activities, a data protection impact assessment or an ethics application. The same for all transcripts. Applies to ResearchTranscript {v}; how an older run came about is stated in the transcription record.",
    "t.schritte": "What the app does with a recording", "t.schritt": "Step", "t.werkzeug": "Tool", "t.wo": "Where",
    "t.schritte.zeilen": "Read the audio track, convert to 16 kHz mono :: macOS AVFoundation :: locally, in the app\n"
                         "Speaker diarisation, can be switched off :: SpeakerKit (Argmax) with pyannote and WeSpeaker models, Core ML :: locally, in the app\n"
                         "Speech recognition :: whisper.cpp {whisper}, model as chosen; without speaker diarisation with Silero VAD {silero} :: locally, helper program from the app bundle, graphics processor\n"
                         "Correction in the editor, with history and journal :: ResearchTranscript :: locally\n"
                         "Export to text, table and archive formats; MP3 via LAME :: ResearchTranscript :: locally, into the chosen folder",
    "t.schutz": "Safeguards the app provides",
    "t.schutz.punkte": "macOS App Sandbox: access only to folders the person chooses in the dialog, and to files dragged in.\n"
                       "No server, no open port, no account.\n"
                       "Saving in a single step; before each save a state goes into the history (30 states).\n"
                       "Deleting moves to the library's trash; nothing is lost immediately.\n"
                       "Journal per transcript: who (installation ID, optionally e-mail) changed what and when.\n"
                       "Zotero is only read, and only after authorisation.\n"
                       "Source code open, app signed.",
    "t.nicht": "What the app does not do",
    "t.nicht.punkte": "It transmits no recordings, texts or usage data: no telemetry, no update check, no crash reports of its own. The macOS network entitlement is set because the built-in web view requires it; a firewall shows that no connection is made. Crash reports by macOS follow the system settings.\n"
                      "It downloads neither models nor program components.\n"
                      "The models do not learn from the recordings.\n"
                      "It summarises nothing and rephrases nothing. Speech recognition is an AI model and can produce words that were not said; hence the check against the recording.",
    "t.ablage": "Where data are stored",
    "t.ablage.punkte": "In the chosen library folder, one subfolder per transcript: `transkript.json` (wording, speakers, memos, journal, Zotero details), a copy of the recording, for video the video file, `wellenform.json`.\n"
                       "`ausgang.json` holds the state as delivered by the machine or by an imported file. `history/` holds the last 30 states. Both contain the wording before any pseudonymisation.\n"
                       "Deleted transcripts remain in the `_papierkorb` folder until it is emptied in the Finder.\n"
                       "During a run, working copies of the audio lie in the app's temporary folder.\n"
                       "Settings and the app log are stored in the app container of the user account. The log contains timestamps, commands, folder and file names, and error messages.",
    "t.person": "What the app stores about researchers",
    "t.person.punkte": "A random installation ID, unrelated to device or person.\n"
                       "Optionally an e-mail address. Both appear in the journal of every transcript and travel with the enrich dossier.",
    "t.export": "What exports contain",
    "t.export.punkte": "All text formats (VTT, CSV, TXT, Markdown, Word): wording, speaker names, timestamps. CSV, Markdown and Word additionally the memos.\n"
                       "Markdown and Word: with a Zotero link, a header with title, date, citekey and the persons whose roles were selected.\n"
                       "REFI-QDA (`.qdpx.zip`): text, memos and the audio recording, i.e. the voice; on request the video file.\n"
                       "enrich dossier (`.enrich`): text, audio recording as MP3, journal with installation ID and e-mail, Zotero details. No memos.",

    # ---- 2b Controller details ----
    "s.titel": "Details from the controller",
    "s.einleitung": "The app cannot know these details. Without them an entry in the records of processing activities is incomplete.",
    "s.felder": "Controller :: institution, project lead, contact\n"
                "Data protection adviser :: responsible person or body\n"
                "Purpose :: research project, research question\n"
                "Legal basis, applicable law :: depending on the institution, cantonal law, federal law or the GDPR\n"
                "Data subjects :: interviewees, third parties mentioned, the researchers themselves (journal)\n"
                "Categories of personal data :: voice, statements, sensitive personal data where applicable\n"
                "Recipients :: who receives recordings, transcripts or exports\n"
                "Disclosure abroad :: none by the app; possible through sharing or cloud storage\n"
                "Retention and deletion :: periods, also for trash, history, baseline, backups\n"
                "Storage location of the library :: internal disk, encrypted drive, network drive\n"
                "Backup and synchronisation :: Time Machine, iCloud Drive and others capture the folder if it lies there\n"
                "Device protection :: FileVault, screen lock, separate user accounts\n"
                "Persons with access :: who works on the computer and in the folder\n"
                "Information and consent :: does it cover recording, transcription, retention, sharing",
    "s.achten": "Points to watch",
    "s.achten.punkte": "“Local” is a property of the app, not of the storage location. A synchronised folder transmits the data.\n"
                       "What is pseudonymised is the text of the final version. Recording, baseline and history still contain the voice and real names.\n"
                       "The researchers' own models are not part of the app's documented list.",
    "s.entfernen": "Removing an interview completely",
    "s.entfernen.text": "For example after consent is withdrawn. The app deletes nothing permanently; these places are to be checked one by one.",
    "s.entfernen.punkte": "Delete the transcript in the app, then empty the library's `_papierkorb` folder in the Finder, and the macOS Trash.\n"
                          "Exports in every place where they were saved or shared.\n"
                          "Backups and synchronised copies of the library folder.\n"
                          "The original recording outside the library.\n"
                          "To remove only the wording before pseudonymisation, delete `ausgang.json` and `history/`. After that, a per-word measure of intervention can no longer be computed.",

    # ---- 3 Data deposit ----
    "r.status": "Status", "r.st.pflicht": "required", "r.st.empfohlen": "recommended", "r.st.optional": "optional",
    "r.vorschlag": "suggestion from Zotero, to be checked",
    "d.titel": "Data sheet: details of the dataset",
    "d.einleitung": "To be completed once per dataset, even if it comprises several interviews. Order and field names follow the Zenodo form; the status refers to Zenodo and DataCite 4.",
    "d.zeilen": "Resource type :: pflicht :: Dataset :: Transcripts together with documentation.\n"
                "Title :: pflicht :: [ … ] :: Descriptive, without names of interviewees.\n"
                "Publication date :: pflicht :: [ … ] :: Date of publication, not of the interview.\n"
                "Creators :: pflicht :: {creators} :: The researchers, with ORCID and institution. Never the interviewees.\n"
                "Description :: empfohlen :: [ … ] :: What it is about, who was interviewed (in general terms), for what purpose.\n"
                "Licence :: pflicht :: [ … ] :: Required by Zenodo for open files. For sensitive files a data use agreement instead of an open licence.\n"
                "Access :: pflicht :: [ … ] :: On Zenodo it applies per record. Open documentation and restricted transcripts as separate, linked records.\n"
                "Contributors :: empfohlen :: [ … ] :: Roles as defined by DataCite, e.g. ContactPerson, DataCollector, RightsHolder.\n"
                "Keywords :: empfohlen :: [ … ] :: Three to eight terms, preferably from a subject vocabulary.\n"
                "Languages :: optional :: {sprachen} :: ISO code of the interview language.\n"
                "Dates (Collected) :: empfohlen :: [ … ] :: Data collection period. If in doubt, the year only.\n"
                "Version :: optional :: 1.0 :: A new version after corrections.\n"
                "Funding :: optional :: [ … ] :: Funder and grant number.\n"
                "Related works :: empfohlen :: {dois} :: DOIs of the articles based on the data.",
    "d.befragte": "Persons of the interviewed side from Zotero are deliberately not listed.",
    "d.archiv": "Specialised archives additionally ask for",
    "d.archiv.punkte": "Data collection method, e.g. semi-structured interview.\n"
                       "Population and selection of interviewees.\n"
                       "Accompanying material: interview guide, information sheet, consent form template, methods report.",
    "i.titel": "Data sheet: details of this interview",
    "i.einleitung": "What the app knows about this one interview, and what belongs with it for the deposit.",
    "i.umfang": "Extent", "i.umfang.wert": "duration {dauer}, {segmente} segments, {sprecher} speakers",
    "i.sprache": "Language", "i.jahr": "Year of data collection", "i.verfahren": "Transcription procedure",
    "i.verfahren.wert": "{app}, whisper.cpp, model {modell}; local; edited by hand (see transcription record)",
    "i.konventionen": "Transcription conventions",
    "i.konventionen.wert": "Timestamps hh:mm:ss per utterance, speaker as a separate field; [ add rules ]",
    "i.pseudonym": "Pseudonymisation", "i.pseudonym.wert": "[ … ] (the pseudonym key is never deposited)",
    "i.formate": "Files for the deposit",
    "i.formate.punkte": "Transcript in an open text format (TXT, Markdown, CSV), in addition to Word and REFI-QDA. Compute checksums after the export.\n"
                        "REFI-QDA is an exchange format with possible loss between programs, not an archival format on its own.\n"
                        "The archival version of the recording is the original file, not re-encoded. The MP3 in the app's packages is an access copy.\n"
                        "The header in the Markdown and Word exports names the persons selected in Zotero. Check before depositing.\n"
                        "The transcription record may be enclosed. `ausgang.json` and `history/` stay out.",
    "e.titel": "Check items before publication",
    "e.einleitung": "Only the researchers can answer these items. What does not apply is marked as such.",
    "e.punkt": "Check item", "e.ja": "met", "e.nz": "does not apply",
    "e.punkte": "The consent covers archiving and reuse. :: Otherwise consult the ethics committee or the data protection adviser.\n"
                "The consent covers sharing of the audio recording. :: The voice is personal data.\n"
                "An ethics approval is on hand. :: State number and body.\n"
                "Direct and indirect identifiers and third parties mentioned have been checked. :: Watch for combinations such as occupation, place and age.\n"
                "Title, description, keywords and file names name no persons. :: Metadata are always public on Zenodo.\n"
                "The pseudonym key is kept separately. :: It never belongs in the deposit.\n"
                "The repository suits the data. :: For sensitive data a specialised archive with access control.\n"
                "Requirements of funder and university have been checked. :: Justify exceptions from open access in the data management plan.",
    "o.titel": "Repositories, formats, requirements",
    "o.einleitung": "The same for all transcripts. The details do not replace the advice of the archive.",
    "o.zenodo": "What Zenodo requires",
    "o.zenodo.punkte": "Sensitive personal data must be appropriately anonymised or covered by consent before open dissemination. For sensitive data that are not anonymised, Zenodo refers to specialised platforms. Responsibility lies with the person who uploads.\n"
                       "Metadata are always public, even when files are restricted.\n"
                       "A published DOI record cannot be deleted without trace.\n"
                       "Limits: 50 GB and 100 files per record.",
    "o.repos": "Repositories", "o.repo": "Repository", "o.fuer": "Suitability",
    "o.repos.zeilen": "Zenodo :: General-purpose, DOI immediately. For documentation, instruments and truly anonymised texts, not for recordings. :: https://zenodo.org\n"
                      "SWISSUbase :: Switzerland. Accepts qualitative and sensitive data, with access control and data use agreement. DOI. :: https://www.swissubase.ch\n"
                      "Qualiservice :: Germany, qualitative data. Advice, help with anonymisation, access on application. DOI. :: https://www.qualiservice.org\n"
                      "AUSSDA :: Austria, social sciences. Dedicated policy for qualitative data. :: https://aussda.at\n"
                      "UK Data Service :: United Kingdom. Tiered access. :: https://ukdataservice.ac.uk",
    "o.vorgaben": "Requirements and guides",
    "o.vorgaben.punkte": "Zenodo, fields: <https://help.zenodo.org/docs/deposit/describe-records/>\n"
                         "Zenodo, policies and terms: <https://about.zenodo.org/policies/> · <https://about.zenodo.org/terms/>\n"
                         "DataCite Metadata Schema 4: <https://schema.datacite.org>\n"
                         "SWISSUbase and FORS, depositing data: <https://forscenter.ch/deposit-data/>\n"
                         "FORS Guide No. 20, anonymisation of qualitative data: <https://doi.org/10.24449/FG-2023-00020>\n"
                         "Qualiservice, sharing data: <https://www.qualiservice.org/de/daten-teilen.html>\n"
                         "CESSDA Data Management Expert Guide: <https://dmeg.cessda.eu>\n"
                         "SNSF, Open Research Data: <https://www.snf.ch/de/FAiWVH4WvpKvohw9/thema/forschungsdaten>\n"
                         "DFG, handling of research data: <https://www.dfg.de/de/grundlagen-themen/grundlagen-und-prinzipien-der-foerderung/forschungsdaten>\n"
                         "README template of Cornell University (CC0): <https://data.research.cornell.edu/data-management/sharing/readme/>",
}
