"""Texts of the companion documents — English. Keys and placeholders identical to de.py."""

T = {
    # ---- general ----
    "feld": "Field", "wert": "Value", "datei": "File", "groesse": "Size", "nachweise": "References",
    "nicht_aufgezeichnet": "not recorded", "dezimal": ".",
    "kopf.erzeugt": "Generated by ResearchTranscript {v} on {datum}. Open fields are marked `[ … ]` "
                    "and are to be completed by the researchers.",
    "modell.mitgeliefert": "shipped with the app", "modell.eigen": "the researchers' own model",
    "modell.unbekannt": "origin not recorded",
    "modell.heute": "— origin according to the present state of the installation, not recorded at the time of the run",
    "diar.aus": "none (switched off)", "diar.an": "SpeakerKit (Argmax) with pyannote community-1, Core ML",
    "diar.auto": "automatic", "diar.zahl": "number of speakers:", "diar.trennung": "clustering threshold",
    "vad.aus": "not used", "ort.lokal": "locally on the Mac, inside the app process; no transmission by the app",

    "f.kennung": "Identifier", "f.name": "Name in the library", "f.quelldatei": "Source file",
    "f.dauer": "Duration", "f.sprache": "Language (setting)", "f.segmente": "Segments",
    "f.sprecher": "Speakers (number)", "f.memos": "Memos (number)", "f.datum": "Date of the run",
    "f.app": "Software", "f.erkennung": "Speech recognition", "f.modell": "Model", "f.modell.satz": "model",
    "f.vad": "Voice activity detection", "f.trennung": "Speaker diarisation", "f.ort": "Place of processing",
    "f.sitzungen": "Editing sessions according to the journal", "f.zeitraum": "Period of editing",
    "f.journal": "Changed entries according to the journal", "f.wer": "Edited by",
    "f.abgehoert": "Checked against the recording by listening", "f.regeln": "Transcription rules",
    "f.pseudonym": "Pseudonymisation",
    "journal.arten": "text {text} · speaker assignment {sprecher} · timing {zeit} · new {neu} · removed {weg} · "
                     "speaker renamed {name}",
    "offen.wer": "[ … ] (name or role; the app does not record this)",
    "offen.abgehoert": "[ in full / in part / no ]",
    "offen.regeln": "[ … ] (e.g. Dresing & Pehl, simple or extended; own rules)",
    "offen.pseudonym": "[ … ] (what was replaced and by which rule; the pseudonym key is kept separately)",

    # ---- documentation package ----
    "paket.ordner": "researchtranscript-documentation", "paket.liesmich": "README",
    "paket.protokolle": "records", "paket.titel": "Documentation package",
    "paket.text": "Companion documents for the selected transcripts, each as Markdown and as a Word file. "
                  "Open fields `[ … ]` are to be completed by the researchers. The package contains no "
                  "transcripts and no recordings.",
    "paket.bib": "citation file for Zotero (File › Import): the software and all sources cited",

    # ---- 1. Transcription record ----
    "datei.protokoll": "transcription-record",
    "p.titel": "Transcription record",
    "p.einleitung": "This record documents how the transcript came about and how heavily it was edited by hand. "
                    "It belongs to the documentation of the individual data object and may accompany the data "
                    "package. The details are taken from the transcript's journal; the record contains no "
                    "names of speakers.",
    "p.aufnahme": "Recording and transcript", "p.maschine": "Machine transcription",
    "p.importiert": "This transcript was not transcribed in the app but imported from `{datei}`. "
                    "The baseline is the file as it arrived.",
    "p.hand": "Editing by hand", "p.mass": "Measure of intervention", "p.dateien": "Files",
    "dateien.hinweis": "Files in the transcript's folder, with checksums. `ausgang.json` is the unaltered "
                       "baseline against which the measure of intervention is computed.",

    "mass.kopf.mass": "Measure", "mass.kopf.basis": "Basis",
    "mass.norm": "Correction rate, word level, normalised",
    "mass.orth": "Correction rate, word level, orthographic",
    "mass.sdi": "{s} substituted, {d} deleted, {i} inserted; {n} words in the final version",
    "mass.sprechzeit": "Reassigned speech time",
    "mass.sprechzeit.basis": "speech time compared {zeit}; {a} speakers in the baseline, {b} in the final version",
    "mass.sprechzeit.mehrheit": "of which, not counting merged speakers",
    "mass.sprechzeit.mehrheit.text": "Mapping several machine speakers to the same person is permitted: "
                                     "merging two voices does not count here",
    "mass.ohne_maschine": "the machine assigned no speakers; all assignments were made by hand",
    "mass.fehlt": "No baseline is available any more for this transcript (created before version 0.6.0; the "
                  "history does not reach back far enough). A correction rate cannot be computed. As an "
                  "indication: {n} of {gesamt} segments ({anteil}) carry the mark “changed by hand”.",
    "mass.aus_verlauf": "The baseline was taken from the oldest state in the history that nobody had yet edited.",
    "mass.definition": "**Definitions.** Correction rate = (substituted + deleted + inserted words) ÷ words of the "
                       "final version, computed like the word error rate (WER) with the final version as the "
                       "reference and the baseline as the hypothesis. *Normalised*: lower-cased, without "
                       "punctuation and special characters; umlauts and accents are kept. *Orthographic*: words "
                       "as written; capitalisation and punctuation count. Reassigned speech time = share of the "
                       "speech time whose speaker in the final version differs from the speaker in the baseline, "
                       "under the best possible one-to-one mapping of speakers; this corresponds to the "
                       "confusion component of the diarization error rate, without a tolerance collar. Missed or "
                       "falsely detected speech is not covered.",
    "mass.vorbehalt": "A measure of intervention, not a measure of accuracy. The rate includes every change made "
                      "by hand, including pseudonymisation, smoothing and transcription rules. It does not "
                      "capture errors that nobody noticed. It quantifies how heavily the text was edited — not "
                      "how good the machine or the final version is.",

    # ---- 2. Methods building block ----
    "datei.methoden": "methods-transcription",
    "m.titel": "Methods building block: transcription",
    "m.einleitung": "A methods section describes the corpus, not the individual interview. This building block "
                    "summarises the selected transcripts: scope, procedure and how heavily the raw machine "
                    "transcripts were edited by hand. Below it are a paragraph to adopt and a list of what "
                    "only the researchers know.",
    "m.korpus": "Corpus", "m.n": "Transcripts", "m.importiert": "of which {n} imported, not transcribed in the app",
    "m.gesamt": "Total duration", "m.mittel": "Duration: mean (range)",
    "m.eigen": "including a model of the researchers' own, not part of the list shipped with the app",
    "m.diar": "for {n} of {gesamt} transcripts (SpeakerKit, pyannote community-1)",
    "m.zeitraum": "Period of the machine runs",
    "m.mass": "Measure of intervention across the corpus",
    "m.mass.text": "Computed for {n} of {gesamt} transcripts (no baseline is available for the others).",
    "m.median": "Median (range)",
    "m.absatz": "Paragraph for the methods section",
    "m.absatz.hinweis": "To be adopted and adapted. Square brackets are to be replaced.",
    "m.absatz.text": "The recordings (n = {n}; total duration {gesamt}; mean {mittel}, range {spanne}) were "
                     "transcribed with ResearchTranscript {version} (B/IAS Basel, AGPL-3.0) entirely locally [ on a "
                     "computer of the research group ]; the app transmits nothing to external services in the "
                     "process. Speech recognition used whisper.cpp {whisper} with the model {modell} (Radford et "
                     "al., 2022).{diar} The raw transcripts were then checked against the recording [ by whom ] "
                     "[ in full / on a sample basis ], corrected according to [ transcription rules ] [ and "
                     "pseudonymised in the text ]. The word-level correction rate (computed like the word error "
                     "rate, final version as the reference, normalised) had a median of {norm}. The rate measures "
                     "the intervention, including pseudonymisation, not the accuracy.",
    "m.absatz.diar": " Speakers were separated with SpeakerKit and the model pyannote community-1 (Plaquet & "
                     "Bredin, 2023); the share of speech time reassigned by hand had a median of {sprechzeit}.",
    "m.offen": "What only the researchers know",
    "m.offen.wer": "Who made the corrections, with what qualification, and whether the recording was listened to in full.",
    "m.offen.regeln": "Which transcription rules were followed (verbatim wording, smoothing, pauses, dialect).",
    "m.offen.pseudonym": "What was pseudonymised and by which rule; where the pseudonym key is kept.",
    "m.offen.einwilligung": "Whether the interviewees' consent covers the kind of processing and any later sharing.",
    "m.je": "Per transcript",

    # ---- 3. Processing building block ----
    "datei.verfahren": "processing-building-block-researchtranscript",
    "v.titel": "Building block for records of processing activities, data protection impact assessment (DPIA) "
               "and ethics application",
    "v.einleitung": "These documents describe a processing activity or a project, not the individual recording. "
                    "This building block supplies the facts about the app as it is installed on this computer. "
                    "Everything that only the controller knows appears below as an open field. The building "
                    "block is not legal advice and makes no statement on lawfulness.",
    "v.schritte": "What the app does with a recording", "v.schritt": "Step", "v.werkzeug": "Tool",
    "v.wo": "Where",
    "v.s1.a": "Read the audio track and convert it to 16 kHz mono", "v.s1.b": "macOS AVFoundation",
    "v.s1.c": "locally, inside the app process",
    "v.s2.a": "Detect voice activity", "v.s2.b": "Silero VAD {silero} in whisper.cpp", "v.s2.c": "locally",
    "v.s3.a": "Speech recognition: audio to text with timestamps",
    "v.s3.b": "whisper.cpp {whisper} (helper program inside the app bundle), model as chosen",
    "v.s3.c": "locally, graphics processor (Metal)",
    "v.s4.a": "Speaker diarisation (can be switched off)", "v.s4.b": "SpeakerKit (Argmax) with pyannote community-1, Core ML",
    "v.s4.c": "locally, Neural Engine",
    "v.s5.a": "Correction in the editor; history and journal per transcript", "v.s5.b": "ResearchTranscript",
    "v.s5.c": "locally",
    "v.s6.a": "Export (VTT, CSV, TXT, Markdown, Word, REFI-QDA, enrich dossier; MP3 via LAME)",
    "v.s6.b": "ResearchTranscript", "v.s6.c": "locally, into the folder the person chooses",
    "v.modelle": "Speech recognition models currently available on this computer:", "v.herkunft": "Origin",
    "v.nicht": "What the app does not do",
    "v.nicht.punkte": "It opens no network connections: no account, no telemetry, no update check, no crash reports of its own. Links (privacy policy, source code) are opened in the browser only on click.\n"
                      "It downloads no models and no program components.\n"
                      "It runs no server and no network service; processing takes place inside the app process.\n"
                      "It runs in the macOS App Sandbox and reads only folders the person has chosen and files the person drags in.\n"
                      "It contains no generative AI: nothing is summarised, rephrased or interpreted.\n"
                      "It reads Zotero only after explicit authorisation and never modifies it.",
    "v.ablage": "Where data are stored",
    "v.ablage.punkte": "In the library folder the person chooses; one subfolder per transcript with `transkript.json`, a copy of the recording (for video, additionally the video file) and `wellenform.json`.\n"
                       "`ausgang.json` holds the unaltered machine baseline, `history/` the last 30 states before each save. Both contain the wording BEFORE any pseudonymisation.\n"
                       "Deleted transcripts remain in the library's `_papierkorb` folder until it is emptied in the Finder.\n"
                       "Settings and the app's log are stored in the app container of the user account; the log may contain file names and error messages.\n"
                       "The app does not know where the library folder is located or whether it is backed up or synchronised.",
    "v.export": "What exports contain",
    "v.export.punkte": "VTT, TXT: text only. CSV, Markdown, Word: text and the researchers' memos.\n"
                       "REFI-QDA (`.qdpx.zip`) and enrich dossier (`.enrich`): additionally the audio recording, i.e. the voice; with video, the video file on request.\n"
                       "enrich dossier: in addition the journal (with the e-mail address, if one is stored in the settings) and linked Zotero metadata.",
    "v.offen": "To be completed by the controller",
    "v.offen.text": "The app cannot know these details. Without them the entry is incomplete.",
    "v.eintrag": "Entry", "v.hinweis": "Note",
    "v.offen.felder": "Controller :: institution, project lead, contact\n"
                      "Data protection adviser or officer :: responsible person or body\n"
                      "Purpose of the processing :: research project, research question\n"
                      "Legal basis and applicable law :: depending on the institution, cantonal law, federal law or the GDPR; the app does not know this\n"
                      "Data subjects :: interviewees; third parties mentioned in the conversation\n"
                      "Categories of personal data :: voice, statements; sensitive personal data where applicable\n"
                      "Recipients :: who receives recordings, transcripts or exports\n"
                      "Disclosure abroad :: none by the app; possible through sharing exports or cloud storage\n"
                      "Retention and deletion :: periods; also for the trash, history, baseline and backups\n"
                      "Storage location of the library folder :: internal disk, encrypted drive, network drive\n"
                      "Backup and synchronisation :: Time Machine, iCloud Drive, other services — they capture the folder if it is located there\n"
                      "Device protection :: FileVault, screen lock, separate user accounts\n"
                      "Persons with access :: who may work on the computer and in the folder\n"
                      "Information and consent of the interviewees :: does it cover recording, transcription, retention, sharing?",
    "v.warnung": "Points to watch",
    "v.warnung.punkte": "Pseudonymised is not anonymised: pseudonymised data remain personal data.\n"
                        "What is pseudonymised is the text of the final version. Recording, baseline and history still contain the voice and real names; whoever no longer needs them deletes them in the Finder.\n"
                        "“Local” is a property of the app, not of the storage location: a synchronised folder transmits the data.\n"
                        "The researchers' own models are not part of the list shipped and documented with the app.",

    # ---- 4. Repository data sheet ----
    "datei.repositorium": "repository-data-sheet",
    "r.dok": "Repository data sheet",
    "r.einleitung": "Preparation for depositing {n} transcript(s) as research data with a DOI. The fields follow "
                    "DataCite 4 and the Zenodo form, supplemented by what specialised archives for qualitative "
                    "data require. What the app knows from Zotero and the transcripts is filled in and marked as "
                    "a suggestion; everything else is open. The sheet replaces neither the advice of the "
                    "archive nor legal advice.",
    "r.warnung": "Read first",
    "r.warnung.punkte": "The audio recording contains the voice and is personal data. It is not published openly, not even under a pseudonym.\n"
                        "Pseudonymised does not mean anonymous; data protection law continues to apply.\n"
                        "Zenodo's terms of use require that sensitive personal data be appropriately anonymised or covered by consent before open dissemination, and refer to specialised platforms for sensitive data that are not anonymised. Responsibility lies with the person who uploads.\n"
                        "Metadata (title, description, keywords, file names) are always public, even when the files are restricted. They must not contain personal data.\n"
                        "A published DOI record cannot be deleted without trace.\n"
                        "Interviewees never appear as creators. From Zotero the app suggests only persons who do not belong to the interviewed side; every suggestion is to be checked.\n"
                        "The transcript is machine-generated and edited by hand; the state of correction belongs in the documentation (transcription record, methods building block).",
    "r.status": "Status", "r.erlaeuterung": "Explanation", "r.vorschlag": "suggestion, to be checked",
    "r.st.pflicht": "required", "r.st.empfohlen": "recommended", "r.st.optional": "optional",
    "r.st.archiv": "required by specialised archives",
    "r.befragte_weg": "(Persons of the interviewed side from Zotero are deliberately not listed.)",
    "r.g.beschreibung": "Description", "r.g.personen": "Persons and roles", "r.g.rechte": "Rights and access",
    "r.g.methode": "Content and method", "r.g.dateien": "Files", "r.g.ethik": "Ethics and data protection",
    "r.titel": "Title of the dataset", "r.titel.e": "Descriptive, without names of interviewees.",
    "r.typ": "Resource type", "r.typ.e": "A package of transcripts and documentation counts as a Dataset.",
    "r.pubdatum": "Publication date", "r.pubdatum.e": "Date of publication in the repository, not of the interview.",
    "r.abstract": "Description", "r.abstract.e": "What it is about, who was interviewed (in general terms) and for what purpose.",
    "r.schlagworte": "Keywords", "r.schlagworte.e": "Three to eight terms, preferably from a subject vocabulary.",
    "r.sprache": "Language(s)", "r.sprache.e": "Language of the interviews as an ISO code.",
    "r.erhebung": "Data collection period", "r.erhebung.e": "If in doubt, year or month only: an exact date can make persons identifiable.",
    "r.ort": "Place or region", "r.ort.e": "Only so precise that nobody becomes identifiable.",
    "r.version": "Version", "r.version.e": "Create a new version after corrections.",
    "r.publisher": "Repository", "r.publisher.e": "Name of the chosen repository (automatic on Zenodo).",
    "r.verwandt": "Related publications", "r.verwandt.e": "DOIs of the articles based on the data.",
    "r.foerderung": "Funding", "r.foerderung.e": "Funder and grant number; the SNSF and the DFG expect this information.",
    "r.creators": "Creators", "r.creators.e": "The researchers responsible for the dataset, with ORCID and institution. Never the interviewees.",
    "r.contributors": "Contributors with role", "r.contributors.e": "e.g. DataCollector, ProjectLeader, Supervisor (roles as defined by DataCite).",
    "r.kontakt": "Contact person", "r.kontakt.e": "Who will answer access requests, also some years from now.",
    "r.rechteinhaber": "Rights holder", "r.rechteinhaber.e": "Usually the university or the researchers.",
    "r.lizenz": "Licence", "r.lizenz.e": "Required for open files, e.g. CC BY 4.0 for the documentation; for sensitive files a data use agreement instead of an open licence.",
    "r.zugang": "Access level per file", "r.zugang.e": "Open, restricted or closed — separately for documentation, transcript and recording.",
    "r.embargo": "Embargo until", "r.embargo.e": "Deferral with justification, e.g. until publication.",
    "r.bedingungen": "Conditions for access requests", "r.bedingungen.e": "Who is granted access, and subject to which conditions.",
    "r.methode": "Data collection method", "r.methode.e": "e.g. semi-structured (guided) interview, on site or online.",
    "r.sampling": "Selection of interviewees", "r.sampling.e": "Population and how the selection was made.",
    "r.umfang": "Extent", "r.umfang.e": "Key technical figures from the transcripts.",
    "r.umfang.wert": "{n} interview(s), total duration {dauer}",
    "r.technik": "Transcription procedure", "r.technik.e": "Machine-generated, edited by hand; add the state of correction from the methods building block.",
    "r.technik.wert": "ResearchTranscript {version}, whisper.cpp {whisper}, model {modell}; local",
    "r.konventionen": "Transcription conventions", "r.konventionen.e": "Notation for pauses, overlaps, unintelligible passages; add here whatever goes beyond the format.",
    "r.konventionen.wert": "Timestamps hh:mm:ss per utterance, speaker as a separate field; [ add rules ]",
    "r.anonymisierung": "Anonymisation", "r.anonymisierung.e": "What was replaced and how; the pseudonym key itself is never deposited.",
    "r.begleit": "Accompanying material", "r.begleit.e": "Interview guide, information sheet, consent form template, methods report, README.",
    "r.dateien.text": "Files as they lie in the library, with checksums (SHA-256). For the deposit, exports are "
                      "generated from them; the checksums of the exports are to be computed after export.",
    "r.formate": "On the formats:",
    "r.formate.punkte": "Deposit transcripts in an open text format (TXT, Markdown, CSV) in addition to Word and REFI-QDA; archives prefer simple, open formats.\n"
                        "REFI-QDA is an exchange format with possible loss between programs, not an archival format on its own.\n"
                        "The MP3 in the app's packages is an access copy. As the archival master, archives recommend FLAC or WAV — that is, the original recording.\n"
                        "Every transcript needs a header with identifier, date and context; the app's Markdown and Word exports write it.",
    "r.ethik.text": "To be answered by the researchers alone. As long as any item is open, nothing is published.",
    "r.pruefpunkt": "Check item", "r.erledigt": "done",
    "r.ethik.punkte": "The consent covers archiving and reuse. :: No sharing without documented consent.\n"
                      "The consent covers sharing of the audio recording. :: The voice is personal data.\n"
                      "An ethics approval or a condition imposed by an ethics committee is on hand. :: State number and body.\n"
                      "Direct and indirect identifiers and third parties mentioned have been checked. :: Watch for combinations such as occupation, place and age.\n"
                      "Title, description, keywords and file names are free of personal data. :: Metadata are always public.\n"
                      "The pseudonym key is kept separately. :: It never belongs in the deposit.\n"
                      "Baseline and history stay out. :: `ausgang.json` and `history/` contain the wording before pseudonymisation.\n"
                      "The repository suits the data. :: For sensitive data, a specialised archive with access control.\n"
                      "Requirements of funder and university have been checked. :: Justify exceptions from open access in the data management plan.",
    "r.wohin": "Which repository", "r.repo": "Repository", "r.repo.fuer": "Suitability",
    "r.repos": "Zenodo :: General-purpose, DOI immediately; files can be restricted, metadata always open. For documentation, instruments and truly anonymised texts; not for recordings. :: https://zenodo.org\n"
               "SWISSUbase (FORS) :: Switzerland, social sciences; accepts qualitative and sensitive data with access control and data use agreement; DOI. :: https://www.swissubase.ch\n"
               "Qualiservice :: Germany, qualitative data; advice, help with anonymisation, access on application only; DOI. :: https://www.qualiservice.org\n"
               "AUSSDA :: Austria, social sciences; dedicated policy for qualitative data. :: https://aussda.at\n"
               "UK Data Service :: United Kingdom; tiered access (open, safeguarded, controlled). :: https://ukdataservice.ac.uk",
    "r.quellen": "Sources",
    "r.quellen.punkte": "DataCite Metadata Schema 4: <https://schema.datacite.org>\n"
                        "Zenodo: fields <https://help.zenodo.org/docs/deposit/describe-records/>, policies <https://about.zenodo.org/policies/>, terms <https://about.zenodo.org/terms/>\n"
                        "CESSDA Data Management Expert Guide: <https://dmeg.cessda.eu>\n"
                        "FORS Guide No. 20, anonymisation of qualitative data: <https://doi.org/10.24449/FG-2023-00020>\n"
                        "SNSF, Open Research Data: <https://www.snf.ch/de/FAiWVH4WvpKvohw9/thema/forschungsdaten>\n"
                        "DFG, handling of research data: <https://www.dfg.de/de/grundlagen-themen/grundlagen-und-prinzipien-der-foerderung/forschungsdaten>\n"
                        "README template of Cornell University (CC0): <https://data.research.cornell.edu/data-management/sharing/readme/>",
    # ---- Methodenbaustein für EIN Transkript (der Regelfall) ----
    'm.einleitung.eins': 'This building block describes how this one transcript came about and how much the machine-generated raw transcript was edited by hand. The statements apply to this document. Below are a paragraph to adopt and a list of what only the researchers know.',
    'm.korpus.eins': 'Transcript',
    'm.mass.fehlt': 'No baseline is available for this transcript any more; the measure of intervention cannot be calculated (see the transcription record).',
    'm.absatz.text.eins': 'The recording (duration {gesamt}) was transcribed entirely locally [ on a computer of the research group ] with ResearchTranscript {version} (B/IAS Basel, AGPL-3.0); the app transmits nothing to external services in the process. Speech recognition used whisper.cpp {whisper} with the model {modell} (Radford et al., 2022).{diar} The raw transcript was then checked against the recording [ by whom ] [ in full / on a sample basis ], corrected according to [ transcription conventions ] [ and pseudonymised in the text ]. The correction rate at word level (calculated like the word error rate, final version as reference, normalised) was {norm}. The rate measures the intervention including pseudonymisation, not accuracy.',
    'm.absatz.diar.eins': ' Speakers were separated with SpeakerKit and the model pyannote community-1 (Plaquet & Bredin, 2023); {sprechzeit} of the speech time was reassigned by hand.',
}
